/**
 * Generated by Computer — app/intake/capture.tsx
 * S-05: Photo Capture — camera + gallery picker with guidance overlay.
 * Vertical slice uses mocked image picker (real camera in full build P3-01/P3-02).
 * Source: photo_intake_engine_spec.docx §3.2; TheBeginning_WorkOrder_v1.0.docx §4.7
 */

import { useState } from 'react';
import { View, Text, Pressable, Image, ScrollView, Alert } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as ImagePicker from 'expo-image-picker';
import { useIntakeStore } from '@/store/intake';
import { CATEGORY_MAP } from '@/types/categories';
import { APP_CONFIG } from '@/config/app';

export default function CaptureScreen() {
  const router = useRouter();
  const { selectedCategory, selectedProtocol, capturedPhotos, addPhoto, removePhoto } = useIntakeStore();
  const catConfig = selectedCategory ? CATEGORY_MAP[selectedCategory] : null;
  const [isPickerOpen, setIsPickerOpen] = useState(false);

  const canProceed = capturedPhotos.length >= APP_CONFIG.minPhotosRequired;
  const atMax = capturedPhotos.length >= APP_CONFIG.maxPhotosPerItem;

  async function handlePickImage() {
    if (atMax) {
      Alert.alert('Max Photos', `You can add up to ${APP_CONFIG.maxPhotosPerItem} photos per item.`);
      return;
    }
    setIsPickerOpen(true);
    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      quality: 1,
      allowsMultipleSelection: false,
    });
    setIsPickerOpen(false);
    if (!result.canceled && result.assets[0]) {
      addPhoto(result.assets[0].uri);
    }
  }

  async function handleCamera() {
    if (atMax) {
      Alert.alert('Max Photos', `You can add up to ${APP_CONFIG.maxPhotosPerItem} photos per item.`);
      return;
    }
    const permission = await ImagePicker.requestCameraPermissionsAsync();
    if (!permission.granted) {
      Alert.alert('Camera Permission', 'Camera access is needed to photograph items.');
      return;
    }
    setIsPickerOpen(true);
    const result = await ImagePicker.launchCameraAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      quality: 1,
    });
    setIsPickerOpen(false);
    if (!result.canceled && result.assets[0]) {
      addPhoto(result.assets[0].uri);
    }
  }

  function handleProceed() {
    router.push('/intake/processing');
  }

  return (
    <SafeAreaView className="flex-1 bg-[#0a0a0a]">
      <View className="flex-1">
        {/* Category guidance */}
        {catConfig && (
          <View className="px-4 pt-4 pb-2 bg-[#141414] border-b border-[#27272a]">
            <View className="flex-row items-center gap-2 mb-1">
              <Text className="text-xl">{catConfig.icon}</Text>
              <Text className="text-[#f4f4f5] font-bold">{catConfig.label}</Text>
              <Text className="text-[#a1a1aa]">·</Text>
              <Text className="text-[#a1a1aa] text-sm uppercase font-semibold">{selectedProtocol}</Text>
            </View>
            <Text className="text-[#a1a1aa] text-sm">{catConfig.cameraGuidance}</Text>
          </View>
        )}

        {/* Photo strip */}
        <ScrollView
          horizontal
          className="max-h-28 border-b border-[#27272a]"
          contentContainerStyle={{ padding: 12, gap: 8, flexDirection: 'row' }}
        >
          {capturedPhotos.map((uri, i) => (
            <View key={uri} className="relative">
              <Image source={{ uri }} className="w-20 h-20 rounded-lg" />
              <Pressable
                onPress={() => removePhoto(uri)}
                className="absolute -top-2 -right-2 bg-[#ef4444] rounded-full w-5 h-5 items-center justify-center"
              >
                <Text className="text-white text-xs font-bold">×</Text>
              </Pressable>
            </View>
          ))}
          {!atMax && (
            <Pressable
              onPress={handlePickImage}
              className="w-20 h-20 rounded-lg border-2 border-dashed border-[#27272a] items-center justify-center"
            >
              <Text className="text-[#52525b] text-2xl">+</Text>
            </Pressable>
          )}
        </ScrollView>

        <Text className="text-center text-[#a1a1aa] text-xs py-2">
          {capturedPhotos.length} / {APP_CONFIG.maxPhotosPerItem} photos · More photos = higher accuracy
        </Text>

        {/* Photo slots guide */}
        {catConfig && (
          <ScrollView className="flex-1 px-4">
            <Text className="text-[#a1a1aa] text-xs font-semibold tracking-widest mb-3 mt-2">RECOMMENDED SHOTS</Text>
            {catConfig.photoSlots.id.map((slot) => (
              <View key={slot.num} className="flex-row gap-3 mb-3">
                <View className="w-7 h-7 rounded-full bg-[#1c1c1c] items-center justify-center">
                  <Text className="text-[#6366f1] font-bold text-xs">{slot.num}</Text>
                </View>
                <View className="flex-1">
                  <Text className="text-[#f4f4f5] font-semibold text-sm">{slot.label}</Text>
                  <Text className="text-[#a1a1aa] text-xs">{slot.tip}</Text>
                </View>
              </View>
            ))}
          </ScrollView>
        )}

        {/* Action buttons */}
        <View className="px-4 pb-6 pt-3 gap-3 border-t border-[#27272a]">
          <View className="flex-row gap-3">
            <Pressable
              onPress={handleCamera}
              disabled={isPickerOpen || atMax}
              className="flex-1 bg-[#1c1c1c] border border-[#27272a] rounded-2xl py-4 items-center active:opacity-70"
            >
              <Text className="text-[#f4f4f5] font-semibold">📷  Camera</Text>
            </Pressable>
            <Pressable
              onPress={handlePickImage}
              disabled={isPickerOpen || atMax}
              className="flex-1 bg-[#1c1c1c] border border-[#27272a] rounded-2xl py-4 items-center active:opacity-70"
            >
              <Text className="text-[#f4f4f5] font-semibold">🖼️  Gallery</Text>
            </Pressable>
          </View>
          <Pressable
            onPress={handleProceed}
            disabled={!canProceed}
            className="bg-[#6366f1] rounded-2xl py-5 items-center active:opacity-80"
            style={{ opacity: canProceed ? 1 : 0.4 }}
          >
            <Text className="text-white font-bold text-lg">
              Analyze {capturedPhotos.length} Photo{capturedPhotos.length !== 1 ? 's' : ''} →
            </Text>
          </Pressable>
        </View>
      </View>
    </SafeAreaView>
  );
}
