/**
 * Generated by Computer — app/intake/category.tsx
 * S-03: Category Select — 7-tile grid.
 * Source: photo_intake_engine_spec.docx §3.2; reseller_v4_final.jsx
 */

import { View, Text, Pressable, FlatList } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useIntakeStore } from '@/store/intake';
import { CATEGORIES } from '@/types/categories';
import type { Category } from '@/types/item';

export default function CategoryScreen() {
  const router = useRouter();
  const setCategory = useIntakeStore((s) => s.setCategory);
  const selected = useIntakeStore((s) => s.selectedCategory);

  function handleSelect(cat: Category) {
    setCategory(cat);
    router.push('/intake/protocol');
  }

  return (
    <SafeAreaView className="flex-1 bg-[#0a0a0a]" edges={['bottom']}>
      <View className="flex-1 px-4 pt-4">
        <Text className="text-[#a1a1aa] text-sm mb-6">
          What type of item are you adding?
        </Text>
        <FlatList
          data={CATEGORIES}
          numColumns={2}
          keyExtractor={(c) => c.id}
          columnWrapperStyle={{ gap: 12 }}
          contentContainerStyle={{ gap: 12 }}
          renderItem={({ item: cat }) => (
            <Pressable
              onPress={() => handleSelect(cat.id)}
              className="flex-1 rounded-2xl p-5 active:scale-95"
              style={{
                backgroundColor: cat.color + '22',
                borderWidth: 2,
                borderColor: selected === cat.id ? cat.color : 'transparent',
              }}
            >
              <Text className="text-4xl mb-2">{cat.icon}</Text>
              <Text className="text-[#f4f4f5] font-bold text-lg">{cat.label}</Text>
              <Text className="text-[#a1a1aa] text-sm">{cat.sub}</Text>
            </Pressable>
          )}
        />
      </View>
    </SafeAreaView>
  );
}
