/**
 * Generated by Computer — app/intake/processing.tsx
 * S-06: Processing — real step labels tied to AnalysisProgressStep enum.
 * FIX: Work Order P3-04 — no fake spinners; real step labels.
 * Uses stubbed AI response for vertical slice when no API key is set.
 * Source: photo_intake_engine_spec.docx §3.2; TheBeginning_WorkOrder_v1.0.docx §4.7
 */

import { useEffect, useRef } from 'react';
import { View, Text, ActivityIndicator } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useIntakeStore } from '@/store/intake';
import { useInventoryStore } from '@/store/inventory';
import { useSessionStore } from '@/store/session';
import { analyzeItem, getApiKey } from '@/lib/api';
import { validateAIResponse } from '@/lib/validation/schemas';
import { generateSKU } from '@/lib/sku';
import type { AnalysisProgressStep, Item } from '@/types/item';
import { STUB_AI_RESPONSE } from '@/lib/stubs';
import * as Crypto from 'expo-crypto';

const STEP_LABELS: Record<AnalysisProgressStep, string> = {
  uploading: 'Uploading photos...',
  identifying: 'Identifying item...',
  pulling_comps: 'Pulling market comps...',
  building_listings: 'Building listing copy...',
  generating_record: 'Generating inventory record...',
  complete: 'Done!',
  error: 'Analysis failed',
};

export default function ProcessingScreen() {
  const router = useRouter();
  const { selectedCategory, selectedProtocol, capturedPhotos, setProgress, setAIResult, setAnalysisError, progress } = useIntakeStore();
  const addItem = useInventoryStore((s) => s.addItem);
  const { incrementUsage, canAddItem } = useSessionStore();
  const hasRun = useRef(false);

  useEffect(() => {
    if (hasRun.current) return;
    hasRun.current = true;
    runAnalysis();
  }, []);

  async function runAnalysis() {
    if (!selectedCategory || !selectedProtocol) {
      setAnalysisError('Missing category or protocol. Please restart.');
      return;
    }

    if (!canAddItem()) {
      setAnalysisError('Free tier limit reached (10 items/month). Upgrade to Pro to continue.');
      return;
    }

    try {
      const apiKey = await getApiKey();
      let rawResult;

      if (!apiKey) {
        // Use stub response for demo/dev without API key
        await simulateStubProgress(selectedProtocol === 'core');
        rawResult = STUB_AI_RESPONSE(selectedCategory, selectedProtocol);
      } else {
        rawResult = await analyzeItem({
          category: selectedCategory,
          protocol: selectedProtocol,
          photoUris: capturedPhotos,
          onProgress: setProgress,
        });
      }

      // Validate with Zod
      const validation = validateAIResponse(rawResult);
      if (!validation.success) {
        setAnalysisError(
          `AI response validation failed:\n${validation.errors.slice(0, 3).join('\n')}`
        );
        return;
      }

      setAIResult(validation.data);

      // Build and save item
      const itemIndex = useInventoryStore.getState().items.length + 1;
      const sku = generateSKU(selectedCategory, itemIndex);
      const id = await Crypto.randomUUID();

      const now = new Date().toISOString();
      const item: Item = {
        id,
        sku,
        category: selectedCategory,
        protocol: selectedProtocol,
        identification: validation.data.itemData.identification,
        confidence: validation.data.itemData.confidence,
        confidenceNotes: validation.data.itemData.confidenceNotes,
        photos: capturedPhotos,
        research: validation.data.research,
        listings: validation.data.listings,
        status: 'Intake',
        statusHistory: [{ status: 'Intake', timestamp: now }],
        listedPlatforms: [],
        sale: null,
        createdAt: now,
        updatedAt: now,
        schemaVersion: 1,
      };

      addItem(item);
      incrementUsage();

      setProgress('complete');
      router.replace(`/intake/result/${id}`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Unknown error';
      setAnalysisError(msg);
      setProgress('error');
    }
  }

  async function simulateStubProgress(isCore: boolean) {
    const steps: AnalysisProgressStep[] = isCore
      ? ['uploading', 'identifying', 'pulling_comps', 'building_listings', 'generating_record']
      : ['uploading', 'identifying', 'generating_record'];
    for (const step of steps) {
      setProgress(step);
      await new Promise((r) => setTimeout(r, 600));
    }
  }

  const isError = progress === 'error' || !!useIntakeStore.getState().analysisError;
  const errorMsg = useIntakeStore((s) => s.analysisError);

  return (
    <SafeAreaView className="flex-1 bg-[#0a0a0a] items-center justify-center px-8">
      {isError ? (
        <View className="items-center">
          <Text className="text-5xl mb-4">⚠️</Text>
          <Text className="text-[#ef4444] text-xl font-bold mb-3 text-center">Analysis Failed</Text>
          <Text className="text-[#a1a1aa] text-sm text-center mb-8">{errorMsg}</Text>
          <Text
            onPress={() => router.back()}
            className="text-[#6366f1] font-semibold"
          >
            ← Go Back
          </Text>
        </View>
      ) : (
        <View className="items-center w-full">
          <ActivityIndicator size="large" color="#6366f1" className="mb-8" />
          <Text className="text-[#f4f4f5] text-xl font-bold mb-2">Analyzing...</Text>
          <Text className="text-[#6366f1] text-base">
            {progress ? STEP_LABELS[progress] : 'Starting...'}
          </Text>
          <View className="mt-8 w-full gap-2">
            {(Object.keys(STEP_LABELS) as AnalysisProgressStep[])
              .filter((s) => s !== 'error' && s !== 'complete')
              .map((step) => {
                const steps: AnalysisProgressStep[] = ['uploading', 'identifying', 'pulling_comps', 'building_listings', 'generating_record'];
                const currentIdx = steps.indexOf(progress as AnalysisProgressStep);
                const stepIdx = steps.indexOf(step);
                const isDone = currentIdx > stepIdx;
                const isActive = currentIdx === stepIdx;
                return (
                  <View key={step} className="flex-row items-center gap-3">
                    <View
                      className="w-2 h-2 rounded-full"
                      style={{
                        backgroundColor: isDone ? '#22c55e' : isActive ? '#6366f1' : '#27272a',
                      }}
                    />
                    <Text
                      className="text-sm"
                      style={{
                        color: isDone ? '#22c55e' : isActive ? '#f4f4f5' : '#52525b',
                      }}
                    >
                      {STEP_LABELS[step]}
                    </Text>
                  </View>
                );
              })}
          </View>
        </View>
      )}
    </SafeAreaView>
  );
}
