/**
 * Generated by Computer — app/intake/protocol.tsx
 * S-04: Protocol Select — QUICK-ADD vs CORE.
 * Source: photo_intake_engine_spec.docx §2.2, §3.2
 */

import { View, Text, Pressable } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useIntakeStore } from '@/store/intake';
import type { Protocol } from '@/types/item';

const PROTOCOLS: { id: Protocol; label: string; time: string; cost: string; desc: string; outputs: string[] }[] = [
  {
    id: 'quick',
    label: 'QUICK-ADD',
    time: '~15 seconds',
    cost: '~$0.02',
    desc: 'Fast identification and inventory row. No comps or listings.',
    outputs: ['Item ID', 'Confidence score', 'SKU', 'Clipboard-ready row'],
  },
  {
    id: 'core',
    label: 'CORE',
    time: '~45 seconds',
    cost: '~$0.08',
    desc: 'Full analysis with market comps, weighted pricing, and platform listings.',
    outputs: ['Everything in QUICK-ADD', '3-comp pricing', 'Target + min prices', 'eBay / FB / TCGPlayer / Mercari listings'],
  },
];

export default function ProtocolScreen() {
  const router = useRouter();
  const setProtocol = useIntakeStore((s) => s.setProtocol);
  const selected = useIntakeStore((s) => s.selectedProtocol);
  const category = useIntakeStore((s) => s.selectedCategory);

  function handleSelect(p: Protocol) {
    setProtocol(p);
    router.push('/intake/capture');
  }

  return (
    <SafeAreaView className="flex-1 bg-[#0a0a0a]" edges={['bottom']}>
      <View className="flex-1 px-4 pt-4 gap-4">
        {category && (
          <Text className="text-[#a1a1aa] text-sm">Category: <Text className="text-[#f4f4f5] font-semibold">{category}</Text></Text>
        )}
        {PROTOCOLS.map((p) => (
          <Pressable
            key={p.id}
            onPress={() => handleSelect(p.id)}
            className="bg-[#141414] border-2 rounded-2xl p-5 active:opacity-80"
            style={{ borderColor: selected === p.id ? '#6366f1' : '#27272a' }}
          >
            <View className="flex-row justify-between items-start mb-2">
              <Text className="text-[#f4f4f5] font-bold text-xl">{p.label}</Text>
              <View className="items-end">
                <Text className="text-[#6366f1] font-semibold text-sm">{p.time}</Text>
                <Text className="text-[#52525b] text-xs">{p.cost}</Text>
              </View>
            </View>
            <Text className="text-[#a1a1aa] text-sm mb-3">{p.desc}</Text>
            {p.outputs.map((o) => (
              <Text key={o} className="text-[#f4f4f5] text-sm py-0.5">· {o}</Text>
            ))}
          </Pressable>
        ))}
      </View>
    </SafeAreaView>
  );
}
