// Generated by Computer — metro.config.js
// NativeWind v4 requires the withNativeWind wrapper on Metro config.
const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');

const config = getDefaultConfig(__dirname);

module.exports = withNativeWind(config, { input: './global.css' });
