/**
 * Generated by Computer — store/intake.ts
 * Ephemeral intake session state — not persisted.
 * Holds the in-progress intake flow data as user moves through screens.
 * Cleared on completion or cancellation.
 */

import { create } from 'zustand';
import type { Category, Protocol, AIResponse, AnalysisProgressStep } from '@/types/item';

interface IntakeState {
  // Step 1: Category
  selectedCategory: Category | null;
  setCategory: (cat: Category) => void;

  // Step 2: Protocol
  selectedProtocol: Protocol | null;
  setProtocol: (p: Protocol) => void;

  // Step 3: Photos
  capturedPhotos: string[];   // local file URIs
  addPhoto: (uri: string) => void;
  removePhoto: (uri: string) => void;
  clearPhotos: () => void;

  // Step 4: Analysis
  progress: AnalysisProgressStep | null;
  setProgress: (step: AnalysisProgressStep) => void;

  // Step 5: Result
  aiResult: AIResponse | null;
  setAIResult: (result: AIResponse) => void;
  analysisError: string | null;
  setAnalysisError: (err: string | null) => void;

  // Reset entire intake session
  reset: () => void;
}

const initialState = {
  selectedCategory: null,
  selectedProtocol: null,
  capturedPhotos: [],
  progress: null,
  aiResult: null,
  analysisError: null,
};

export const useIntakeStore = create<IntakeState>()((set) => ({
  ...initialState,

  setCategory: (cat) => set({ selectedCategory: cat }),
  setProtocol: (p) => set({ selectedProtocol: p }),

  addPhoto: (uri) =>
    set((state) => ({
      capturedPhotos: [...state.capturedPhotos, uri].slice(0, 8), // max 8
    })),
  removePhoto: (uri) =>
    set((state) => ({
      capturedPhotos: state.capturedPhotos.filter((p) => p !== uri),
    })),
  clearPhotos: () => set({ capturedPhotos: [] }),

  setProgress: (step) => set({ progress: step }),
  setAIResult: (result) => set({ aiResult: result }),
  setAnalysisError: (err) => set({ analysisError: err }),

  reset: () => set(initialState),
}));
