/**
 * Generated by Computer — store/inventory.ts
 * Zustand inventory store. Single source of truth for all item records.
 * Source: TheBeginning_WorkOrder_v1.0.docx §3.2
 */

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import type { Item, ItemStatus, Category } from '@/types/item';
import { APP_CONFIG } from '@/config/app';

interface InventoryState {
  items: Item[];
  isLoaded: boolean;

  // CRUD
  addItem: (item: Item) => void;
  updateItem: (id: string, updates: Partial<Item>) => void;
  deleteItem: (id: string) => void;
  getItemById: (id: string) => Item | undefined;

  // Bulk ops
  updateStatus: (ids: string[], status: ItemStatus) => void;
  deleteItems: (ids: string[]) => void;

  // Derived
  getItemsByCategory: (category: Category) => Item[];
  getItemsByStatus: (status: ItemStatus) => Item[];
  getTotalInventoryValue: () => number;
}

export const useInventoryStore = create<InventoryState>()(
  persist(
    (set, get) => ({
      items: [],
      isLoaded: false,

      addItem: (item) =>
        set((state) => ({ items: [item, ...state.items] })),

      updateItem: (id, updates) =>
        set((state) => ({
          items: state.items.map((i) =>
            i.id === id
              ? { ...i, ...updates, updatedAt: new Date().toISOString() }
              : i
          ),
        })),

      deleteItem: (id) =>
        set((state) => ({ items: state.items.filter((i) => i.id !== id) })),

      getItemById: (id) => get().items.find((i) => i.id === id),

      updateStatus: (ids, status) =>
        set((state) => ({
          items: state.items.map((i) =>
            ids.includes(i.id)
              ? {
                  ...i,
                  status,
                  updatedAt: new Date().toISOString(),
                  statusHistory: [
                    ...i.statusHistory,
                    { status, timestamp: new Date().toISOString() },
                  ],
                }
              : i
          ),
        })),

      deleteItems: (ids) =>
        set((state) => ({ items: state.items.filter((i) => !ids.includes(i.id)) })),

      getItemsByCategory: (category) => get().items.filter((i) => i.category === category),

      getItemsByStatus: (status) => get().items.filter((i) => i.status === status),

      getTotalInventoryValue: () =>
        get()
          .items.filter((i) => i.research?.targetSellPrice)
          .reduce((sum, i) => sum + (i.research?.targetSellPrice ?? 0), 0),
    }),
    {
      name: APP_CONFIG.STORAGE_KEYS.INVENTORY,
      storage: createJSONStorage(() => AsyncStorage),
      onRehydrateStorage: () => (state) => {
        if (state) state.isLoaded = true;
      },
    }
  )
);
