/**
 * Generated by Computer — store/session.ts
 * Zustand session store — usage tracking, freemium gating, onboarding state.
 * Source: TheBeginning_WorkOrder_v1.0.docx §3.2; photo_intake_engine_spec.docx §5.2
 */

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { APP_CONFIG } from '@/config/app';

interface SessionState {
  totalItemsAllTime: number;
  itemsThisMonth: number;
  monthKey: string;         // 'YYYY-MM' — resets counter when month changes
  onboardingComplete: boolean;
  isPro: boolean;           // TODO: wire to RevenueCat in Phase 5
  lastSyncedAt: string | null;

  // Derived
  canAddItem: () => boolean;
  remainingFreeItems: () => number;

  // Mutations
  incrementUsage: () => void;
  markOnboardingComplete: () => void;
  setIsPro: (val: boolean) => void;
  setLastSynced: (ts: string) => void;
}

function currentMonthKey(): string {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
}

export const useSessionStore = create<SessionState>()(
  persist(
    (set, get) => ({
      totalItemsAllTime: 0,
      itemsThisMonth: 0,
      monthKey: currentMonthKey(),
      onboardingComplete: false,
      isPro: false,
      lastSyncedAt: null,

      canAddItem: () => {
        const state = get();
        if (state.isPro) return true;
        // Auto-reset monthly counter if we've rolled into a new month
        const mk = currentMonthKey();
        const count = state.monthKey !== mk ? 0 : state.itemsThisMonth;
        return count < APP_CONFIG.freeTierMonthlyLimit;
      },

      remainingFreeItems: () => {
        const state = get();
        if (state.isPro) return Infinity;
        const mk = currentMonthKey();
        const count = state.monthKey !== mk ? 0 : state.itemsThisMonth;
        return Math.max(0, APP_CONFIG.freeTierMonthlyLimit - count);
      },

      incrementUsage: () =>
        set((state) => {
          const mk = currentMonthKey();
          const prevCount = state.monthKey !== mk ? 0 : state.itemsThisMonth;
          return {
            totalItemsAllTime: state.totalItemsAllTime + 1,
            itemsThisMonth: prevCount + 1,
            monthKey: mk,
          };
        }),

      markOnboardingComplete: () => set({ onboardingComplete: true }),

      setIsPro: (val) => set({ isPro: val }),

      setLastSynced: (ts) => set({ lastSyncedAt: ts }),
    }),
    {
      name: APP_CONFIG.STORAGE_KEYS.SESSION_STATS,
      storage: createJSONStorage(() => AsyncStorage),
    }
  )
);
