/**
 * Generated by Computer — store/ui.ts
 * Global UI state: active modals, toast queue, loading states.
 * Source: TheBeginning_WorkOrder_v1.0.docx §3.2 (uiStore requirement)
 */

import { create } from 'zustand';

export interface Toast {
  id: string;
  type: 'success' | 'error' | 'warning' | 'info';
  message: string;
  duration?: number;  // ms, default 3000
}

interface UIState {
  // Toast queue
  toasts: Toast[];
  addToast: (toast: Omit<Toast, 'id'>) => void;
  removeToast: (id: string) => void;
  clearToasts: () => void;

  // Global loading
  isGlobalLoading: boolean;
  setGlobalLoading: (val: boolean) => void;

  // Active modal tracker
  activeModal: string | null;
  openModal: (name: string) => void;
  closeModal: () => void;
}

let _toastId = 0;

export const useUIStore = create<UIState>()((set) => ({
  toasts: [],
  isGlobalLoading: false,
  activeModal: null,

  addToast: (toast) =>
    set((state) => ({
      toasts: [
        ...state.toasts,
        { ...toast, id: String(++_toastId) },
      ],
    })),

  removeToast: (id) =>
    set((state) => ({ toasts: state.toasts.filter((t) => t.id !== id) })),

  clearToasts: () => set({ toasts: [] }),

  setGlobalLoading: (val) => set({ isGlobalLoading: val }),

  openModal: (name) => set({ activeModal: name }),

  closeModal: () => set({ activeModal: null }),
}));

/** Convenience helper — call from anywhere to show a toast */
export function showToast(toast: Omit<Toast, 'id'>) {
  useUIStore.getState().addToast(toast);
}
