/**
 * Generated by Computer — types/categories.ts
 * Category enum + UI config + identification field metadata.
 * Source: reseller_v4_final.jsx + photo_intake_engine_spec.docx §4.2
 */

import type { Category } from './item';

export interface CategoryConfig {
  id: Category;
  label: string;
  sub: string;
  icon: string;
  color: string;
  tailwindColor: string;
  photoSlots: {
    id: PhotoSlot[];
    listing?: PhotoSlot[];
  };
  cameraGuidance: string;
}

export interface PhotoSlot {
  num: number;
  label: string;
  tip: string;
}

export const CATEGORIES: CategoryConfig[] = [
  {
    id: 'SHOE',
    label: 'SHOE',
    sub: 'Sneakers',
    icon: '👟',
    color: '#FF6B35',
    tailwindColor: 'cat-shoe',
    cameraGuidance: 'Capture lateral side, sole, tongue tag, box label',
    photoSlots: {
      id: [
        { num: 1, label: 'Lateral — Stripe Side', tip: 'Single shoe, stripe face up, camera at ankle height. Primary model ID.' },
        { num: 2, label: 'Lateral — Inside Face', tip: 'Flip shoe. Inside panel facing camera, same ankle height.' },
        { num: 3, label: 'Toe Box', tip: 'Shoot straight-on at toe level. Shape + crease + damage visible.' },
        { num: 4, label: 'Heel Counter', tip: 'Directly behind shoe. Brand logo + heel cup condition.' },
        { num: 5, label: 'Sole', tip: 'Bottom of shoe face-up. Sole wear pattern + stitching visible.' },
        { num: 6, label: 'Tongue Tag', tip: 'Pull tongue forward. Size tag + branding fully visible.' },
      ],
    },
  },
  {
    id: 'SLAB',
    label: 'SLAB',
    sub: 'Graded Cards',
    icon: '⬜',
    color: '#FFD700',
    tailwindColor: 'cat-slab',
    cameraGuidance: "Capture front of slab — cert number visible",
    photoSlots: {
      id: [
        { num: 1, label: 'Slab Front', tip: 'Card front fully visible through case. Cert number readable. No glare.' },
        { num: 2, label: 'Slab Back', tip: 'Reverse of slab — grade label, barcode, certifying company logo.' },
        { num: 3, label: 'Case Edges', tip: 'All four edges. Case condition, cracks, yellowing.' },
      ],
    },
  },
  {
    id: 'RAW',
    label: 'RAW',
    sub: 'Raw Singles',
    icon: '🃏',
    color: '#00E5FF',
    tailwindColor: 'cat-raw',
    cameraGuidance: 'Capture card front, back, and any defects under bright light',
    photoSlots: {
      id: [
        { num: 1, label: 'Card Front', tip: 'Flat on white background. Full card visible. No shadows.' },
        { num: 2, label: 'Card Back', tip: 'Back of card — centering and print quality visible.' },
        { num: 3, label: 'Top Edge', tip: 'Close-up of top edge. Whitening, chips, dings.' },
        { num: 4, label: 'Bottom Edge', tip: 'Bottom edge condition.' },
      ],
    },
  },
  {
    id: 'SEAL',
    label: 'SEAL',
    sub: 'Sealed Product',
    icon: '📦',
    color: '#69FF47',
    tailwindColor: 'cat-seal',
    cameraGuidance: 'Capture all sides of sealed packaging — seals and language visible',
    photoSlots: {
      id: [
        { num: 1, label: 'Front Face', tip: 'Product name, set logo, and art fully visible.' },
        { num: 2, label: 'Back Face', tip: 'Contents listed, set code, language indicator.' },
        { num: 3, label: 'Factory Seal', tip: 'Shrink wrap or seal strip — intact or broken clearly visible.' },
      ],
    },
  },
  {
    id: 'APRL',
    label: 'APRL',
    sub: 'Apparel',
    icon: '👕',
    color: '#BF5AF2',
    tailwindColor: 'cat-aprl',
    cameraGuidance: 'Capture front, back, tag, and any wear or defects',
    photoSlots: {
      id: [
        { num: 1, label: 'Front Layout', tip: 'Full front of item laid flat. Design and condition visible.' },
        { num: 2, label: 'Back Layout', tip: 'Full back. Back print or plain back clearly shown.' },
        { num: 3, label: 'Tag / Label', tip: 'Size tag + brand tag in neck or waistband.' },
        { num: 4, label: 'Any Damage', tip: 'Close-up of stains, holes, fading, or wear areas.' },
      ],
    },
  },
  {
    id: 'ELEC',
    label: 'ELEC',
    sub: 'Electronics',
    icon: '💻',
    color: '#0A84FF',
    tailwindColor: 'cat-elec',
    cameraGuidance: 'Capture model sticker, serial number, physical condition',
    photoSlots: {
      id: [
        { num: 1, label: 'Front / Screen', tip: 'Device face. Screen on or off. Visible cracks or scratches.' },
        { num: 2, label: 'Model Sticker', tip: 'Serial number, model number, specs label. Must be readable.' },
        { num: 3, label: 'Ports / Inputs', tip: 'All ports, inputs, and connectors. Damage or debris visible.' },
        { num: 4, label: 'Physical Condition', tip: 'Back of device. Scratches, dents, missing parts.' },
      ],
    },
  },
  {
    id: 'COLL',
    label: 'COLL',
    sub: 'Collectibles',
    icon: '🎯',
    color: '#FF375F',
    tailwindColor: 'cat-coll',
    cameraGuidance: 'Capture item, packaging, and any identifying marks or numbers',
    photoSlots: {
      id: [
        { num: 1, label: 'Item Front', tip: 'Primary face of collectible. Full item visible.' },
        { num: 2, label: 'Item Back', tip: 'Back or bottom — item number, manufacturer, copyright date.' },
        { num: 3, label: 'Packaging', tip: 'Box or original packaging. Condition, sealed or open.' },
        { num: 4, label: 'Any Defects', tip: 'Close-up of paint chips, scratches, missing accessories.' },
      ],
    },
  },
];

export const CATEGORY_MAP: Record<Category, CategoryConfig> = Object.fromEntries(
  CATEGORIES.map(c => [c.id, c])
) as Record<Category, CategoryConfig>;
