/**
 * Generated by Computer — types/item.ts
 * Full item schema TypeScript types matching Photo Intake Engine Spec v1.0 §4.
 * Source: photo_intake_engine_spec.docx + TheBeginning_WorkOrder_v1.0.docx
 *
 * IMPORTANT: These types are the single source of truth for data shapes.
 * Zod schemas in lib/validation/ must stay in sync with these types.
 */

// ─────────────────────────────────────────────────────────────
// ENUMS
// ─────────────────────────────────────────────────────────────

export type Category = 'SLAB' | 'RAW' | 'SEAL' | 'SHOE' | 'APRL' | 'ELEC' | 'COLL';

export type Protocol = 'quick' | 'core';

export type ItemStatus =
  | 'Intake'
  | 'Photo Queue'
  | 'Research'
  | 'Listed'
  | 'Sold'
  | 'Shipped';

export type VelocityTier = 'Fast Flip' | 'Standard' | 'Long Hold';

export type Platform = 'ebay' | 'facebook' | 'tcgplayer' | 'mercari' | 'stockx' | 'goat';

// ─────────────────────────────────────────────────────────────
// CATEGORY-SPECIFIC IDENTIFICATION FIELDS  (Spec §4.2)
// ─────────────────────────────────────────────────────────────

export interface SlabIdentification {
  cardName: string;
  set: string;
  cardNumber: string;
  game: string;
  gradingCompany: string;   // PSA | BGS | CGC | SGC | ACE
  grade: string;            // e.g. "9", "9.5", "10"
  certNumber: string;
  slabCondition: string;    // outer case condition
  cardVariant?: string;     // Holo | Reverse Holo | 1st Edition | etc.
}

export interface RawIdentification {
  cardName: string;
  set: string;
  cardNumber: string;
  game: string;
  rarity: string;
  quantity: number;
  condition: string;        // NM | LP | MP | HP | DMG
  gradeCandidate: boolean;  // AI-assessed grading potential
}

export interface SealIdentification {
  productType: string;      // Booster Box | ETB | Blister | etc.
  game: string;
  set: string;
  productName: string;
  language: string;
  quantity: number;
  packagingCondition: string;
}

export interface ShoeIdentification {
  brand: string;
  model: string;
  colorway: string;
  styleCode: string;
  size: string;
  condition: string;
  boxIncluded: boolean;
  boxCondition?: string;
}

export interface AprlIdentification {
  brand: string;
  itemType: string;
  gender: string;
  size: string;
  color: string;
  material: string;
  condition: string;
}

export interface ElecIdentification {
  brand: string;
  productType: string;
  modelNumber: string;
  modelName: string;
  serialNumber?: string;
  functionalStatus: string; // Fully Working | Powers On | Parts Only | Untested
  physicalCondition: string;
  processor?: string;
  ram?: string;
  storage?: string;
}

export interface CollIdentification {
  brand: string;
  productLine: string;
  characterName?: string;
  series?: string;
  itemNumber?: string;
  variant?: string;
  retailerExclusive?: string;
  condition: string;
  boxCondition?: string;
}

export type CategoryIdentification =
  | SlabIdentification
  | RawIdentification
  | SealIdentification
  | ShoeIdentification
  | AprlIdentification
  | ElecIdentification
  | CollIdentification;

// ─────────────────────────────────────────────────────────────
// COMP / RESEARCH STRUCTURE  (Spec §4.3)
// ─────────────────────────────────────────────────────────────

export interface Comp {
  price: number;
  source: string;
  date?: string;
  notes?: string;
}

export interface Research {
  comp1: Comp;              // Recent eBay sold — 50% weight
  comp2: Comp;              // Conservative floor — 25% weight
  comp3: Comp;              // Optimistic ceiling — 25% weight
  weightedAvg: number;      // (comp1×0.50) + (comp2×0.25) + (comp3×0.25)
  targetSellPrice: number;  // weightedAvg × 1.07
  minAcceptPrice: number;   // weightedAvg × 0.87
  velocityTier: VelocityTier;
  marketNotes: string;
  popReport?: string;       // SLAB only: population report data
  gradingROI?: string;      // RAW only: estimated ROI if submitted for grading
}

// ─────────────────────────────────────────────────────────────
// LISTING STRUCTURES
// ─────────────────────────────────────────────────────────────

export interface PlatformListing {
  title: string;
  description: string;
  price: number;
  shippingNote?: string;
}

export interface Listings {
  ebay?: PlatformListing;
  facebook?: PlatformListing;
  tcgplayer?: PlatformListing;
  mercari?: PlatformListing;
}

// ─────────────────────────────────────────────────────────────
// STATUS HISTORY LOG
// ─────────────────────────────────────────────────────────────

export interface StatusLogEntry {
  status: ItemStatus;
  timestamp: string;    // ISO 8601
  note?: string;
}

// ─────────────────────────────────────────────────────────────
// SALE RECORD
// ─────────────────────────────────────────────────────────────

export interface SaleRecord {
  salePrice: number;
  platform: Platform;
  buyerUsername?: string;
  saleDate: string;         // ISO date
  platformFee: number;      // calculated from fee schedule
  grossProfit: number;      // salePrice - purchasePrice
  netProfit: number;        // salePrice - purchasePrice - platformFee
  roi: number;              // netProfit / purchasePrice × 100
  shippingCost?: number;
  trackingNumber?: string;
}

// ─────────────────────────────────────────────────────────────
// FULL ITEM RECORD  (Spec §4.1)
// ─────────────────────────────────────────────────────────────

export interface Item {
  id: string;               // UUID, auto-generated
  sku: string;              // [CATEGORY]-[YYMMDD]-[INDEX]
  category: Category;
  protocol: Protocol;
  identification: CategoryIdentification;
  confidence: number;       // 0–100
  confidenceNotes?: string;
  photos: string[];         // local file URIs
  research: Research | null;     // CORE mode only
  listings: Listings | null;     // CORE mode only
  purchaseDate?: string;    // ISO date, user-entered
  purchasePrice?: number;   // user-entered
  purchaseSource?: string;
  storageLocation?: string;
  status: ItemStatus;
  statusHistory: StatusLogEntry[];
  createdAt: string;        // ISO timestamp, auto-set
  updatedAt: string;        // ISO timestamp, auto-set on any update
  listedPlatforms: Platform[];
  sale: SaleRecord | null;  // set when status = Sold
  notes?: string;
  schemaVersion: number;    // for future migration support — current: 1
}

// ─────────────────────────────────────────────────────────────
// AI RESPONSE SHAPE  (what Claude returns per request)
// ─────────────────────────────────────────────────────────────

export interface AIResponse {
  itemData: {
    category: Category;
    identification: CategoryIdentification;
    confidence: number;
    confidenceNotes?: string;
  };
  research: Research | null;
  listings: Listings | null;
  inventoryRow: {
    sku: string;
    name: string;
    category: Category;
    condition: string;
    confidence: number;
    targetSellPrice?: number;
    minAcceptPrice?: number;
    notes?: string;
  };
}

// ─────────────────────────────────────────────────────────────
// ANALYSIS PROGRESS  (for processing screen step display)
// ─────────────────────────────────────────────────────────────

export type AnalysisProgressStep =
  | 'uploading'
  | 'identifying'
  | 'pulling_comps'
  | 'building_listings'
  | 'generating_record'
  | 'complete'
  | 'error';
