/**
 * Generated by Computer — app/_layout.tsx
 * Root layout for Expo Router. Sets dark theme, loads fonts, handles onboarding redirect.
 * Source: photo_intake_engine_spec.docx §6.2; TheBeginning_WorkOrder_v1.0.docx §5.1
 */

import '../global.css';
import { useEffect } from 'react';
import { Stack } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import { SafeAreaProvider } from 'react-native-safe-area-context';

export default function RootLayout() {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <SafeAreaProvider>
        <StatusBar style="light" backgroundColor="#0a0a0a" />
        <Stack
          screenOptions={{
            headerStyle: { backgroundColor: '#0a0a0a' },
            headerTintColor: '#f4f4f5',
            headerTitleStyle: { fontWeight: '700' },
            contentStyle: { backgroundColor: '#0a0a0a' },
            animation: 'slide_from_right',
          }}
        >
          <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
          <Stack.Screen name="onboarding" options={{ headerShown: false, gestureEnabled: false }} />
          <Stack.Screen name="intake/category" options={{ title: 'Select Category' }} />
          <Stack.Screen name="intake/protocol" options={{ title: 'Select Protocol' }} />
          <Stack.Screen name="intake/capture" options={{ title: 'Capture Photos', headerShown: false }} />
          <Stack.Screen name="intake/processing" options={{ headerShown: false, gestureEnabled: false }} />
          <Stack.Screen name="intake/result/[id]" options={{ title: 'Result', headerShown: false }} />
          <Stack.Screen name="item/[id]" options={{ title: 'Item Detail' }} />
        </Stack>
      </SafeAreaProvider>
    </GestureHandlerRootView>
  );
}
