/**
 * Generated by Computer — app/onboarding.tsx
 * S-01: Onboarding flow — multi-step as spec'd in Work Order §4.9.
 * Vertical slice: Step 1 (welcome) + Step 2 (API key) + Step 5 (ready).
 * Full 5-step build is Work Order P4-08 (Phase 4).
 * Source: TheBeginning_WorkOrder_v1.0.docx §4.9
 */

import { useState } from 'react';
import { View, Text, Pressable, TextInput, Alert, KeyboardAvoidingView, Platform } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { saveApiKey } from '@/lib/api';
import { useSessionStore } from '@/store/session';

type Step = 'welcome' | 'api-key' | 'ready';

export default function OnboardingScreen() {
  const router = useRouter();
  const markComplete = useSessionStore((s) => s.markOnboardingComplete);
  const [step, setStep] = useState<Step>('welcome');
  const [apiKey, setApiKey] = useState('');
  const [isSaving, setIsSaving] = useState(false);

  async function handleSaveKey() {
    if (!apiKey.trim()) return;
    setIsSaving(true);
    const result = await saveApiKey(apiKey.trim());
    setIsSaving(false);
    if (result.success) {
      setStep('ready');
    } else {
      Alert.alert('Invalid Key', result.error ?? 'Could not validate key. Check it and try again.');
    }
  }

  function handleComplete() {
    markComplete();
    router.replace('/(tabs)');
  }

  return (
    <SafeAreaView className="flex-1 bg-[#0a0a0a]">
      <KeyboardAvoidingView
        className="flex-1"
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        {step === 'welcome' && (
          <View className="flex-1 px-6 justify-center">
            <Text className="text-[#6366f1] text-sm font-semibold tracking-widest mb-3">
              RUSSELL VAULT LLC
            </Text>
            <Text className="text-[#f4f4f5] text-4xl font-bold mb-2">
              The{'\n'}Beginning
            </Text>
            <Text className="text-[#a1a1aa] text-lg mb-10">
              Photo → AI analysis → inventory record + platform listings in under 60 seconds.
            </Text>
            {[
              '📸  Photograph any resale item',
              '🤖  AI identifies, comps, and writes listings',
              '📋  Copy to spreadsheet or save to inventory',
            ].map((line) => (
              <Text key={line} className="text-[#f4f4f5] text-base mb-3">{line}</Text>
            ))}
            <Pressable
              onPress={() => setStep('api-key')}
              className="mt-12 bg-[#6366f1] rounded-2xl py-5 items-center active:opacity-80"
            >
              <Text className="text-white text-lg font-bold">Get Started</Text>
            </Pressable>
          </View>
        )}

        {step === 'api-key' && (
          <View className="flex-1 px-6 justify-center">
            <Text className="text-[#6366f1] text-sm font-semibold tracking-widest mb-3">STEP 2 OF 5</Text>
            <Text className="text-[#f4f4f5] text-3xl font-bold mb-2">Add Your{'\n'}API Key</Text>
            <Text className="text-[#a1a1aa] text-base mb-6">
              The Beginning uses the Anthropic Claude API. Your key is stored securely on-device only.
              Get yours at{' '}
              <Text className="text-[#6366f1]">console.anthropic.com</Text>
            </Text>
            <TextInput
              className="bg-[#141414] border border-[#27272a] rounded-xl px-4 py-4 text-[#f4f4f5] font-mono text-sm mb-4"
              placeholder="sk-ant-api..."
              placeholderTextColor="#52525b"
              value={apiKey}
              onChangeText={setApiKey}
              secureTextEntry
              autoCapitalize="none"
              autoCorrect={false}
            />
            <Pressable
              onPress={handleSaveKey}
              disabled={isSaving || !apiKey.trim()}
              className="bg-[#6366f1] rounded-2xl py-5 items-center active:opacity-80"
              style={{ opacity: (!apiKey.trim() || isSaving) ? 0.5 : 1 }}
            >
              <Text className="text-white text-lg font-bold">
                {isSaving ? 'Validating...' : 'Save Key & Continue'}
              </Text>
            </Pressable>
            <Pressable onPress={() => setStep('ready')} className="mt-3 py-3 items-center">
              <Text className="text-[#52525b] text-sm">Skip for now (add later in Settings)</Text>
            </Pressable>
          </View>
        )}

        {step === 'ready' && (
          <View className="flex-1 px-6 justify-center items-center">
            <Text className="text-6xl mb-6">✅</Text>
            <Text className="text-[#f4f4f5] text-3xl font-bold mb-2 text-center">You're Ready</Text>
            <Text className="text-[#a1a1aa] text-base text-center mb-12">
              Photograph your first item to see The Beginning in action.
            </Text>
            <Pressable
              onPress={handleComplete}
              className="w-full bg-[#6366f1] rounded-2xl py-5 items-center active:opacity-80"
            >
              <Text className="text-white text-lg font-bold">Add First Item →</Text>
            </Pressable>
          </View>
        )}
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}
