/**
 * Generated by Computer — lib/validation/schemas.ts
 * Zod schemas for every data type. All AI API responses MUST be validated here.
 * FIX: Work Order P1-06 — validate all AI responses before storing.
 * Source: TheBeginning_WorkOrder_v1.0.docx §3.3; types/item.ts
 *
 * CRITICAL: If Claude returns a malformed or partial JSON response, Zod will
 * catch it here and surface a user-facing error before any bad data is stored.
 */

import { z } from 'zod';

// ─────────────────────────────────────────────────────────────
// PRIMITIVE ENUMS
// ─────────────────────────────────────────────────────────────

export const CategorySchema = z.enum(['SLAB', 'RAW', 'SEAL', 'SHOE', 'APRL', 'ELEC', 'COLL']);
export const ProtocolSchema = z.enum(['quick', 'core']);
export const ItemStatusSchema = z.enum(['Intake', 'Photo Queue', 'Research', 'Listed', 'Sold', 'Shipped']);
export const VelocityTierSchema = z.enum(['Fast Flip', 'Standard', 'Long Hold']);
export const PlatformSchema = z.enum(['ebay', 'facebook', 'tcgplayer', 'mercari', 'stockx', 'goat']);

// ─────────────────────────────────────────────────────────────
// CATEGORY-SPECIFIC IDENTIFICATION SCHEMAS
// ─────────────────────────────────────────────────────────────

export const SlabIdentificationSchema = z.object({
  cardName: z.string(),
  set: z.string(),
  cardNumber: z.string(),
  game: z.string(),
  gradingCompany: z.string(),
  grade: z.string(),
  certNumber: z.string(),
  slabCondition: z.string(),
  cardVariant: z.string().optional(),
});

export const RawIdentificationSchema = z.object({
  cardName: z.string(),
  set: z.string(),
  cardNumber: z.string(),
  game: z.string(),
  rarity: z.string(),
  quantity: z.number().int().positive(),
  condition: z.string(),
  gradeCandidate: z.boolean(),
});

export const SealIdentificationSchema = z.object({
  productType: z.string(),
  game: z.string(),
  set: z.string(),
  productName: z.string(),
  language: z.string(),
  quantity: z.number().int().positive(),
  packagingCondition: z.string(),
});

export const ShoeIdentificationSchema = z.object({
  brand: z.string(),
  model: z.string(),
  colorway: z.string(),
  styleCode: z.string(),
  size: z.string(),
  condition: z.string(),
  boxIncluded: z.boolean(),
  boxCondition: z.string().optional(),
});

export const AprlIdentificationSchema = z.object({
  brand: z.string(),
  itemType: z.string(),
  gender: z.string(),
  size: z.string(),
  color: z.string(),
  material: z.string(),
  condition: z.string(),
});

export const ElecIdentificationSchema = z.object({
  brand: z.string(),
  productType: z.string(),
  modelNumber: z.string(),
  modelName: z.string(),
  serialNumber: z.string().optional(),
  functionalStatus: z.string(),
  physicalCondition: z.string(),
  processor: z.string().optional(),
  ram: z.string().optional(),
  storage: z.string().optional(),
});

export const CollIdentificationSchema = z.object({
  brand: z.string(),
  productLine: z.string(),
  characterName: z.string().optional(),
  series: z.string().optional(),
  itemNumber: z.string().optional(),
  variant: z.string().optional(),
  retailerExclusive: z.string().optional(),
  condition: z.string(),
  boxCondition: z.string().optional(),
});

export const CategoryIdentificationSchema = z.union([
  SlabIdentificationSchema,
  RawIdentificationSchema,
  SealIdentificationSchema,
  ShoeIdentificationSchema,
  AprlIdentificationSchema,
  ElecIdentificationSchema,
  CollIdentificationSchema,
]);

// ─────────────────────────────────────────────────────────────
// COMP + RESEARCH
// ─────────────────────────────────────────────────────────────

export const CompSchema = z.object({
  price: z.number().nonnegative(),
  source: z.string(),
  date: z.string().optional(),
  notes: z.string().optional(),
});

export const ResearchSchema = z.object({
  comp1: CompSchema,
  comp2: CompSchema,
  comp3: CompSchema,
  weightedAvg: z.number().nonnegative(),
  targetSellPrice: z.number().nonnegative(),
  minAcceptPrice: z.number().nonnegative(),
  velocityTier: VelocityTierSchema,
  marketNotes: z.string(),
  popReport: z.string().optional(),
  gradingROI: z.string().optional(),
});

// ─────────────────────────────────────────────────────────────
// LISTINGS
// ─────────────────────────────────────────────────────────────

export const PlatformListingSchema = z.object({
  title: z.string(),
  description: z.string(),
  price: z.number().nonnegative(),
  shippingNote: z.string().optional(),
});

export const ListingsSchema = z.object({
  ebay: PlatformListingSchema.optional(),
  facebook: PlatformListingSchema.optional(),
  tcgplayer: PlatformListingSchema.optional(),
  mercari: PlatformListingSchema.optional(),
});

// ─────────────────────────────────────────────────────────────
// AI RESPONSE SCHEMA  (the critical validation boundary)
// ─────────────────────────────────────────────────────────────

export const AIResponseSchema = z.object({
  itemData: z.object({
    category: CategorySchema,
    identification: CategoryIdentificationSchema,
    confidence: z.number().int().min(0).max(100),
    confidenceNotes: z.string().optional(),
  }),
  research: ResearchSchema.nullable(),
  listings: ListingsSchema.nullable(),
  inventoryRow: z.object({
    sku: z.string(),
    name: z.string(),
    category: CategorySchema,
    condition: z.string(),
    confidence: z.number().int().min(0).max(100),
    targetSellPrice: z.number().nonnegative().nullable().optional(),
    minAcceptPrice: z.number().nonnegative().nullable().optional(),
    notes: z.string().optional(),
  }),
});

// ─────────────────────────────────────────────────────────────
// FULL ITEM SCHEMA
// ─────────────────────────────────────────────────────────────

export const StatusLogEntrySchema = z.object({
  status: ItemStatusSchema,
  timestamp: z.string(),
  note: z.string().optional(),
});

export const SaleRecordSchema = z.object({
  salePrice: z.number().nonnegative(),
  platform: PlatformSchema,
  buyerUsername: z.string().optional(),
  saleDate: z.string(),
  platformFee: z.number().nonnegative(),
  grossProfit: z.number(),
  netProfit: z.number(),
  roi: z.number(),
  shippingCost: z.number().nonnegative().optional(),
  trackingNumber: z.string().optional(),
});

export const ItemSchema = z.object({
  id: z.string().uuid(),
  sku: z.string(),
  category: CategorySchema,
  protocol: ProtocolSchema,
  identification: CategoryIdentificationSchema,
  confidence: z.number().int().min(0).max(100),
  confidenceNotes: z.string().optional(),
  photos: z.array(z.string()),
  research: ResearchSchema.nullable(),
  listings: ListingsSchema.nullable(),
  purchaseDate: z.string().optional(),
  purchasePrice: z.number().nonnegative().optional(),
  purchaseSource: z.string().optional(),
  storageLocation: z.string().optional(),
  status: ItemStatusSchema,
  statusHistory: z.array(StatusLogEntrySchema),
  createdAt: z.string(),
  updatedAt: z.string(),
  listedPlatforms: z.array(PlatformSchema),
  sale: SaleRecordSchema.nullable(),
  notes: z.string().optional(),
  schemaVersion: z.number().int().positive(),
});

// ─────────────────────────────────────────────────────────────
// VALIDATION HELPERS
// ─────────────────────────────────────────────────────────────

export type ValidationResult<T> =
  | { success: true; data: T }
  | { success: false; errors: string[] };

/** Validate an AI response. Returns typed data or user-friendly errors. */
export function validateAIResponse(raw: unknown): ValidationResult<z.infer<typeof AIResponseSchema>> {
  const result = AIResponseSchema.safeParse(raw);
  if (result.success) return { success: true, data: result.data };
  const errors = result.error.errors.map(e => `${e.path.join('.')}: ${e.message}`);
  return { success: false, errors };
}

/** Validate a stored item (e.g. during migration or data integrity check) */
export function validateItem(raw: unknown): ValidationResult<z.infer<typeof ItemSchema>> {
  const result = ItemSchema.safeParse(raw);
  if (result.success) return { success: true, data: result.data };
  const errors = result.error.errors.map(e => `${e.path.join('.')}: ${e.message}`);
  return { success: false, errors };
}
