/**
 * Generated by Computer — lib/api.ts
 * Anthropic API wrapper — proxy-friendly, no dangerouslyAllowBrowser.
 * FIX: Work Order P1-02 / P1-03 — secure key handling, valid model name.
 * Source: TheBeginning_WorkOrder_v1.0.docx §2.1, §2.2; photo_intake_engine_spec.docx §5.1
 *
 * SECURITY: The API key is never bundled. It is read at call-time from
 * Expo SecureStore. If a backend proxy is implemented (Phase 2+),
 * replace the `fetch` call target with the proxy URL and remove key
 * injection from the client entirely.
 */

import * as SecureStore from 'expo-secure-store';
import { APP_CONFIG } from '@/config/app';
import { MODEL_PRIMARY, MODEL_FALLBACK, MAX_TOKENS, type ModelName } from './models';
import type { Category, Protocol, AIResponse, AnalysisProgressStep } from '@/types/item';

const ANTHROPIC_API_URL = 'https://api.anthropic.com/v1/messages';
const ANTHROPIC_VERSION = '2023-06-01';

// ─────────────────────────────────────────────────────────────
// KEY MANAGEMENT
// ─────────────────────────────────────────────────────────────

/** Retrieve the stored API key. Returns null if not set. */
export async function getApiKey(): Promise<string | null> {
  return SecureStore.getItemAsync(APP_CONFIG.STORAGE_KEYS.ANTHROPIC_API_KEY);
}

/** Store an API key securely. Validates before saving. */
export async function saveApiKey(key: string): Promise<{ success: boolean; error?: string }> {
  const validation = await validateApiKey(key);
  if (!validation.valid) {
    return { success: false, error: validation.error };
  }
  await SecureStore.setItemAsync(APP_CONFIG.STORAGE_KEYS.ANTHROPIC_API_KEY, key);
  return { success: true };
}

/** Remove the stored API key. */
export async function revokeApiKey(): Promise<void> {
  await SecureStore.deleteItemAsync(APP_CONFIG.STORAGE_KEYS.ANTHROPIC_API_KEY);
}

/**
 * Validate an API key by making a minimal test call.
 * Uses MODEL_FALLBACK (Haiku) to minimise cost of validation ping.
 */
export async function validateApiKey(key: string): Promise<{ valid: boolean; error?: string }> {
  try {
    const response = await fetch(ANTHROPIC_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'anthropic-version': ANTHROPIC_VERSION,
        'x-api-key': key,
      },
      body: JSON.stringify({
        model: MODEL_FALLBACK,
        max_tokens: 10,
        messages: [{ role: 'user', content: 'ping' }],
      }),
      signal: AbortSignal.timeout(10_000),
    });

    if (response.status === 401) return { valid: false, error: 'Invalid API key.' };
    if (response.status === 403) return { valid: false, error: 'API key does not have permission.' };
    // Any 2xx or 4xx other than auth errors means the key format is valid
    return { valid: true };
  } catch (err) {
    return { valid: false, error: 'Network error during key validation.' };
  }
}

// ─────────────────────────────────────────────────────────────
// IMAGE ENCODING  (compression handled in lib/compression/)
// ─────────────────────────────────────────────────────────────

/** Convert a local file URI to base64 string via Expo FileSystem */
export async function readImageAsBase64(uri: string): Promise<string> {
  // Dynamic import to avoid issues in environments without expo-file-system
  const FileSystem = await import('expo-file-system');
  const base64 = await FileSystem.readAsStringAsync(uri, {
    encoding: FileSystem.EncodingType.Base64,
  });
  return base64;
}

// ─────────────────────────────────────────────────────────────
// CORE ANALYSIS CALL
// ─────────────────────────────────────────────────────────────

export interface AnalysisOptions {
  category: Category;
  protocol: Protocol;
  photoUris: string[];
  onProgress?: (step: AnalysisProgressStep) => void;
}

/**
 * Run AI analysis on photos.
 * Steps match AnalysisProgressStep enum for real progress display (Work Order P3-04).
 * Returns raw parsed JSON — caller must validate with Zod schema (lib/validation/).
 */
export async function analyzeItem(options: AnalysisOptions): Promise<AIResponse> {
  const { category, protocol, photoUris, onProgress } = options;

  const apiKey = await getApiKey();
  if (!apiKey) {
    throw new Error('API key not configured. Please add your Anthropic key in Settings.');
  }

  const model: ModelName = protocol === 'quick' ? MODEL_FALLBACK : MODEL_PRIMARY;
  const maxTokens = MAX_TOKENS[protocol];

  // Step 1: Upload (compression happens in compression layer)
  onProgress?.('uploading');

  // Compress + encode all images
  const { compressImage } = await import('./compression');
  const imageContents: object[] = [];
  for (const uri of photoUris) {
    const compressedUri = await compressImage(uri, category);
    const base64 = await readImageAsBase64(compressedUri);
    imageContents.push({
      type: 'image',
      source: {
        type: 'base64',
        media_type: 'image/jpeg',
        data: base64,
      },
    });
  }

  // Step 2: Identify
  onProgress?.('identifying');

  // Build prompts
  const { buildSystemPrompt, buildUserPrompt } = await import('./prompts');
  const systemPrompt = buildSystemPrompt();
  const userPrompt = buildUserPrompt(category, protocol, photoUris.length);

  const messageContent = [
    ...imageContents,
    { type: 'text', text: userPrompt },
  ];

  // Step 3 / 4 (CORE only)
  if (protocol === 'core') {
    onProgress?.('pulling_comps');
  }

  // Make API call with single retry on 5xx (Spec §5.1)
  let response: Response | null = null;
  for (let attempt = 0; attempt <= APP_CONFIG.apiMaxRetries; attempt++) {
    try {
      response = await fetch(ANTHROPIC_API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'anthropic-version': ANTHROPIC_VERSION,
          'x-api-key': apiKey,
        },
        body: JSON.stringify({
          model,
          max_tokens: maxTokens,
          system: systemPrompt,
          messages: [{ role: 'user', content: messageContent }],
        }),
        signal: AbortSignal.timeout(APP_CONFIG.apiTimeoutMs),
      });

      if (response.ok) break;

      // Retry on 5xx only
      const shouldRetry = response.status >= 500 && attempt < APP_CONFIG.apiMaxRetries;
      if (!shouldRetry) break;

      await new Promise(r => setTimeout(r, 2000)); // brief backoff
    } catch (err) {
      if (attempt === APP_CONFIG.apiMaxRetries) throw err;
    }
  }

  if (!response || !response.ok) {
    const status = response?.status ?? 0;
    throw new Error(`API request failed (${status}). Check your key and connection.`);
  }

  if (protocol === 'core') {
    onProgress?.('building_listings');
  }

  // Step 5: Parse response
  onProgress?.('generating_record');

  const data = await response.json();
  const rawText: string = data?.content?.[0]?.text ?? '';

  // Strip any accidental markdown fences
  const cleaned = rawText.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();

  let parsed: AIResponse;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    throw new Error('AI returned malformed JSON. Please retry or use manual entry.');
  }

  onProgress?.('complete');
  return parsed;
}
