/**
 * Generated by Computer — lib/compression.ts
 * Image compression utilities using expo-image-manipulator.
 * FIX: Work Order P1-04 — images must be resized before API submission.
 * Source: TheBeginning_WorkOrder_v1.0.docx §2.3; photo_intake_engine_spec.docx §9.1
 */

import * as ImageManipulator from 'expo-image-manipulator';
import type { Category } from '@/types/item';
import { APP_CONFIG } from '@/config/app';

/**
 * Compress and resize a photo URI before API submission.
 * SLAB category gets a higher resolution ceiling to preserve grade label legibility.
 * Returns the compressed file URI.
 */
export async function compressImage(uri: string, category: Category): Promise<string> {
  const maxDimension =
    category === 'SLAB'
      ? APP_CONFIG.imageMaxDimensionSlab
      : APP_CONFIG.imageMaxDimension;

  const result = await ImageManipulator.manipulateAsync(
    uri,
    [{ resize: { width: maxDimension } }],
    {
      compress: APP_CONFIG.imageQuality,
      format: ImageManipulator.SaveFormat.JPEG,
    }
  );

  if (__DEV__) {
    // TODO: Add actual byte size logging once expo-file-system info() is wired up
    console.log('[compression] Compressed image for category', category, '→', result.uri);
  }

  return result.uri;
}

/**
 * Compress multiple images in sequence.
 * Returns array of compressed URIs in the same order as input.
 */
export async function compressImages(uris: string[], category: Category): Promise<string[]> {
  const results: string[] = [];
  for (const uri of uris) {
    const compressed = await compressImage(uri, category);
    results.push(compressed);
  }
  return results;
}
