/**
 * Generated by Computer — lib/models.ts
 * Anthropic model name constants.
 * FIX: Work Order P1-02 — model name correction (claude-sonnet-4-0 was invalid).
 * Source: TheBeginning_WorkOrder_v1.0.docx §2.2
 *
 * These are the ONLY places model names should appear in the codebase.
 * Never hard-code model strings anywhere else.
 */

/** Primary model — Claude Sonnet 4.5 (latest stable as of work order date) */
export const MODEL_PRIMARY = 'claude-sonnet-4-5-20251101' as const;

/**
 * Fallback model — used for QUICK-ADD calls where cost sensitivity is higher.
 * TODO: Confirm fallback model preference with client.
 * Decision log: Defaulting to Haiku 3.5 for cost-efficiency on quick calls.
 */
export const MODEL_FALLBACK = 'claude-haiku-3-5-20241022' as const;

/** Max tokens per protocol (Spec §5.1) */
export const MAX_TOKENS = {
  core: 4000,
  quick: 1500,
} as const;

export type ModelName = typeof MODEL_PRIMARY | typeof MODEL_FALLBACK;
