/**
 * Generated by Computer — lib/pricing.ts
 * 3-comp weighted average pricing calculation helpers.
 * Source: photo_intake_engine_spec.docx §2.3
 */

import type { Research, Comp } from '@/types/item';

/** 3-comp pricing weights (Spec §2.3) */
const WEIGHTS = { comp1: 0.50, comp2: 0.25, comp3: 0.25 } as const;

/** Multipliers for target/min accept price (Spec §2.3) */
const TARGET_MULTIPLIER = 1.07;
const MIN_ACCEPT_MULTIPLIER = 0.87;

/**
 * Calculate the weighted average from 3 comps.
 * Returns 0 if any comp price is 0 or missing.
 */
export function calcWeightedAverage(comp1: Comp, comp2: Comp, comp3: Comp): number {
  return (
    comp1.price * WEIGHTS.comp1 +
    comp2.price * WEIGHTS.comp2 +
    comp3.price * WEIGHTS.comp3
  );
}

/** Calculate the target sell price from a weighted average */
export function calcTargetSellPrice(weightedAvg: number): number {
  return Math.round(weightedAvg * TARGET_MULTIPLIER * 100) / 100;
}

/** Calculate the minimum acceptable price from a weighted average */
export function calcMinAcceptPrice(weightedAvg: number): number {
  return Math.round(weightedAvg * MIN_ACCEPT_MULTIPLIER * 100) / 100;
}

/**
 * Derive net profit estimate.
 * @param salePrice     - Expected or actual sale price
 * @param purchasePrice - What you paid
 * @param platformFee   - Platform fee as decimal (e.g. 0.13 for 13%)
 * @param shippingCost  - Optional shipping cost
 */
export function calcNetProfit(
  salePrice: number,
  purchasePrice: number,
  platformFee: number,
  shippingCost = 0
): number {
  const fee = salePrice * platformFee;
  return Math.round((salePrice - purchasePrice - fee - shippingCost) * 100) / 100;
}

/** Calculate ROI as percentage */
export function calcROI(netProfit: number, purchasePrice: number): number {
  if (purchasePrice === 0) return 0;
  return Math.round((netProfit / purchasePrice) * 10000) / 100;
}

/**
 * Build a full Research object from comps.
 * Used when manually entering comp data or recalculating.
 */
export function buildResearch(
  comp1: Comp,
  comp2: Comp,
  comp3: Comp,
  velocityTier: Research['velocityTier'],
  marketNotes: string
): Omit<Research, 'popReport' | 'gradingROI'> {
  const weightedAvg = calcWeightedAverage(comp1, comp2, comp3);
  return {
    comp1,
    comp2,
    comp3,
    weightedAvg,
    targetSellPrice: calcTargetSellPrice(weightedAvg),
    minAcceptPrice: calcMinAcceptPrice(weightedAvg),
    velocityTier,
    marketNotes,
  };
}

/** Format a number as USD currency string */
export function formatUSD(value: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
}
