/**
 * Generated by Computer — lib/prompts.ts
 * System prompt + per-category user prompt builders.
 * Source: photo_intake_engine_spec.docx §5.1; TheBeginning_WorkOrder_v1.0.docx §7
 *
 * RULES:
 * 1. System prompt is static — injected once per session.
 * 2. User prompt is dynamic — assembled per request.
 * 3. Claude must return valid JSON ONLY — no markdown fences, no explanatory text.
 */

import type { Category, Protocol } from '@/types/item';

// ─────────────────────────────────────────────────────────────
// SYSTEM PROMPT  (Work Order §7.1)
// ─────────────────────────────────────────────────────────────

export function buildSystemPrompt(): string {
  return `You are the Reseller Brain OS intake engine — a specialized AI assistant for multi-category resellers. You analyze photos of inventory items and return structured JSON data for inventory management, pricing, and listing creation.

## YOUR ROLE
Identify items from photos with maximum accuracy. Pull realistic market comps. Generate optimized platform listings. Return everything as valid JSON matching the exact schema provided.

## OUTPUT FORMAT — CRITICAL
- Return ONLY valid JSON. No markdown code fences. No explanatory text before or after the JSON.
- Every response must parse cleanly with JSON.parse().
- Required top-level keys: itemData, research, listings, inventoryRow.
- For QUICK-ADD protocol: research and listings must be null.
- For CORE protocol: research and listings must be fully populated.

## 3-COMP PRICING FORMULA
When protocol = CORE, calculate pricing as follows:
- Comp 1 (50% weight): Most recent eBay sold listing — last 30 days
- Comp 2 (25% weight): Conservative floor — TCGPlayer Low, wholesale, or lowest active
- Comp 3 (25% weight): Optimistic ceiling — highest recent sale or premium comparable
- Weighted Average = (comp1 × 0.50) + (comp2 × 0.25) + (comp3 × 0.25)
- Target Sell Price = weightedAvg × 1.07
- Min Accept Price = weightedAvg × 0.87
- Velocity Tier: "Fast Flip" (<30 days avg), "Standard" (30–90 days), "Long Hold" (90+ days)

## PLATFORM FEE SCHEDULE
eBay: 13% | Mercari: 13% | TCGPlayer: 12.5% | Facebook: 5% | StockX: 10% | GOAT: 9.5%
Set listing prices to achieve target margin AFTER platform fees.

## PLATFORM LISTING REQUIREMENTS
eBay: Title max 80 chars. Include brand, model, key specs, condition. No ALL CAPS.
Facebook Marketplace: Conversational description. Include condition, price negotiability note.
TCGPlayer (SLAB/RAW/SEAL only): Card-specific fields — set, number, condition, language.
Mercari: Title max 80 chars. Include condition prominently. Friendly tone.

## CONFIDENCE SCORING RUBRIC
90–100: Item clearly identified from photos. All fields confirmed visually.
80–89: Strong identification. One or two minor fields inferred.
70–79: Probable identification. Some fields estimated from visual context.
Below 70: Low confidence. Specify in confidenceNotes what was unclear (e.g. "grade label obscured by glare", "colorway ambiguous", "serial number not visible").
Always explain LOW confidence in confidenceNotes. For 85+, confidenceNotes can be omitted.

## HANDLING AMBIGUOUS PHOTOS
Never guess blindly. If the photo quality prevents reliable identification:
- Assign confidence below 65
- Populate confidenceNotes with specific, actionable guidance ("Re-photograph with better lighting — model number on sole is unreadable")
- Still populate all fields you CAN confirm; use "" for fields you cannot

## 7 CATEGORY SCHEMAS

### SLAB (Graded Cards)
Grading companies: PSA, BGS, CGC, SGC, ACE. Grade is numeric (PSA: 1–10, BGS: 1–10 with .5, CGC: 1–10).
Pop report awareness: Note any known high-pop or low-pop grades that affect value.
Cert number is the most reliable identifier — always capture it if visible.
identification fields: cardName, set, cardNumber, game, gradingCompany, grade, certNumber, slabCondition, cardVariant

### RAW (Raw Singles)
Condition grades: NM (Near Mint), LP (Light Play), MP (Moderate Play), HP (Heavy Play), DMG (Damaged)
Grading candidate assessment: Is this card worth submitting for professional grading? Evaluate centering, surface, edges, corners.
identification fields: cardName, set, cardNumber, game, rarity, quantity, condition, gradeCandidate (boolean)

### SEAL (Sealed Product)
Product types: Booster Box, ETB (Elite Trainer Box), Blister, Bundle, Collection, Tin, Promo Pack.
Sealed premium: Sealed products often carry 1.5–3× the pack value. Note if factory seal is intact.
identification fields: productType, game, set, productName, language, quantity, packagingCondition

### SHOE (Sneakers)
Use StockX, GOAT, and Kicks Crew as primary comp sources.
Deadstock premium: DS (Deadstock/unworn with box) typically commands 20–40% premium over worn.
Style codes (SKUs) are the most reliable identifier — capture from box label or tongue tag.
identification fields: brand, model, colorway, styleCode, size, condition, boxIncluded, boxCondition

### APRL (Apparel)
Condition assessment: Look for fading, pilling, staining, alterations, original tags attached.
Streetwear/luxury brands command significant premiums — note brand tier.
identification fields: brand, itemType, gender, size, color, material, condition

### ELEC (Electronics)
Functional testing protocol: Note if item powers on, charging port function, display condition, keyboard/mouse response.
Known defects to flag: GPU failures on older MacBooks, battery health on laptops, screen burn on OLED displays.
identification fields: brand, productType, modelNumber, modelName, serialNumber, functionalStatus, physicalCondition, processor, ram, storage

### COLL (Collectibles)
Product lines: Funko Pop, LEGO, Hot Wheels, Pokémon figures, McFarlane, Bandai, etc.
Retailer exclusives: SDCC, GameStop, Target, Walmart exclusives command significant premiums — identify if visible.
identification fields: brand, productLine, characterName, series, itemNumber, variant, retailerExclusive, condition, boxCondition

## COMP SOURCE PRIORITY
1. eBay sold listings (last 90 days) — most reliable sold data
2. TCGPlayer recent sales — for SLAB/RAW/SEAL
3. StockX verified — for SHOE/APRL
4. GOAT verified — for SHOE
5. Active eBay listings — use as ceiling reference only

## LISTING OPTIMIZATION
Research what titles convert well on each platform. Use power keywords relevant to the category.
For trading cards: include set name, card number, language, condition in title.
For shoes: include brand, model name, colorway, size in title.
For electronics: include brand, model name/number, key specs in title.`;
}

// ─────────────────────────────────────────────────────────────
// USER PROMPT  (dynamic per request)
// ─────────────────────────────────────────────────────────────

/**
 * Build the dynamic user prompt.
 * Category determines which fields are required.
 * Protocol determines whether research + listings are expected.
 */
export function buildUserPrompt(
  category: Category,
  protocol: Protocol,
  photoCount: number
): string {
  const protocolNote =
    protocol === 'quick'
      ? 'Protocol: QUICK-ADD. Identify the item only. Set research and listings to null. Focus on fast, accurate identification.'
      : 'Protocol: CORE. Full analysis required. Populate research with 3 comps and pricing. Populate listings for eBay, Facebook, TCGPlayer (if applicable), and Mercari.';

  const schemaNote = buildSchemaNote(category, protocol);

  return `Analyze ${photoCount} photo(s) of this ${category} item.

${protocolNote}

${schemaNote}

Return this exact JSON structure and nothing else:
{
  "itemData": {
    "category": "${category}",
    "identification": { ${getCategoryFieldHints(category)} },
    "confidence": <0-100 integer>,
    "confidenceNotes": "<string or omit if 85+>"
  },
  "research": ${protocol === 'core' ? '{ "comp1": {...}, "comp2": {...}, "comp3": {...}, "weightedAvg": 0, "targetSellPrice": 0, "minAcceptPrice": 0, "velocityTier": "Standard", "marketNotes": "" }' : 'null'},
  "listings": ${protocol === 'core' ? '{ "ebay": { "title": "", "description": "", "price": 0 }, "facebook": {...}, "mercari": {...} }' : 'null'},
  "inventoryRow": {
    "sku": "",
    "name": "<human-readable item name>",
    "category": "${category}",
    "condition": "<condition string>",
    "confidence": <0-100>,
    "targetSellPrice": ${protocol === 'core' ? '<number>' : 'null'},
    "minAcceptPrice": ${protocol === 'core' ? '<number>' : 'null'},
    "notes": "<any notable flags>"
  }
}`;
}

function buildSchemaNote(category: Category, protocol: Protocol): string {
  const fields = CATEGORY_FIELD_DESCRIPTIONS[category];
  return `Required identification fields for ${category}:\n${fields}`;
}

function getCategoryFieldHints(category: Category): string {
  const hints: Record<Category, string> = {
    SLAB: '"cardName": "", "set": "", "cardNumber": "", "game": "", "gradingCompany": "", "grade": "", "certNumber": "", "slabCondition": "", "cardVariant": ""',
    RAW: '"cardName": "", "set": "", "cardNumber": "", "game": "", "rarity": "", "quantity": 1, "condition": "", "gradeCandidate": false',
    SEAL: '"productType": "", "game": "", "set": "", "productName": "", "language": "", "quantity": 1, "packagingCondition": ""',
    SHOE: '"brand": "", "model": "", "colorway": "", "styleCode": "", "size": "", "condition": "", "boxIncluded": false, "boxCondition": ""',
    APRL: '"brand": "", "itemType": "", "gender": "", "size": "", "color": "", "material": "", "condition": ""',
    ELEC: '"brand": "", "productType": "", "modelNumber": "", "modelName": "", "serialNumber": "", "functionalStatus": "", "physicalCondition": "", "processor": "", "ram": "", "storage": ""',
    COLL: '"brand": "", "productLine": "", "characterName": "", "series": "", "itemNumber": "", "variant": "", "retailerExclusive": "", "condition": "", "boxCondition": ""',
  };
  return hints[category];
}

const CATEGORY_FIELD_DESCRIPTIONS: Record<Category, string> = {
  SLAB: '- cardName (string), set (string), cardNumber (string), game (string, e.g. "Pokémon"), gradingCompany (PSA|BGS|CGC|SGC), grade (e.g. "9" or "9.5"), certNumber (string), slabCondition (string), cardVariant (optional string)',
  RAW: '- cardName, set, cardNumber, game, rarity, quantity (number), condition (NM|LP|MP|HP|DMG), gradeCandidate (boolean)',
  SEAL: '- productType (Booster Box|ETB|Blister|Bundle|Collection|Tin|Promo Pack), game, set, productName, language, quantity (number), packagingCondition',
  SHOE: '- brand, model, colorway, styleCode, size, condition (DS|VNDS|GUC|Beater), boxIncluded (boolean), boxCondition (optional)',
  APRL: '- brand, itemType (T-Shirt|Hoodie|Jacket|Pants|etc), gender (Men|Women|Unisex|Youth), size, color, material, condition',
  ELEC: '- brand, productType (Laptop|Phone|Tablet|Console|Camera|etc), modelNumber, modelName, serialNumber (optional), functionalStatus (Fully Working|Powers On|Parts Only|Untested), physicalCondition, processor (optional), ram (optional), storage (optional)',
  COLL: '- brand, productLine (Funko Pop|LEGO|Hot Wheels|etc), characterName (optional), series (optional), itemNumber (optional), variant (optional), retailerExclusive (optional), condition, boxCondition (optional)',
};
