/**
 * Generated by Computer — lib/sku.ts
 * SKU generation logic matching Reseller Brain OS convention.
 * Source: photo_intake_engine_spec.docx §2.4
 * Format: [CATEGORY]-[YYMMDD]-[INDEX]  e.g. SLAB-260306-001
 */

import type { Category } from '@/types/item';

/**
 * Generate a SKU for the current intake session.
 * @param category  - Item category
 * @param index     - Row index within the current session (1-based)
 * @param date      - Optional date override (defaults to today)
 */
export function generateSKU(category: Category, index: number, date?: Date): string {
  const d = date ?? new Date();
  const yy = String(d.getFullYear()).slice(-2);
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  const idx = String(index).padStart(3, '0');
  return `${category}-${yy}${mm}${dd}-${idx}`;
}

/**
 * Parse a SKU string into its components.
 * Returns null if the format is invalid.
 */
export function parseSKU(sku: string): {
  category: Category;
  date: string;
  index: number;
} | null {
  const parts = sku.split('-');
  if (parts.length !== 3) return null;
  const [cat, dateStr, idxStr] = parts;
  const index = parseInt(idxStr, 10);
  if (isNaN(index)) return null;
  return { category: cat as Category, date: dateStr, index };
}
