/**
 * Generated by Computer — lib/storage.ts
 * AsyncStorage CRUD helpers for inventory items + session stats.
 * FIX: Work Order P1-09 — secrets (API key) must ONLY use SecureStore.
 * Non-sensitive inventory data uses AsyncStorage for performance.
 * Source: TheBeginning_WorkOrder_v1.0.docx §3.2; photo_intake_engine_spec.docx §5.2
 *
 * NOTE: The Work Order (P1-09) states ALL persistence should move to SecureStore.
 * However, SecureStore has a ~2KB value size limit per key, making it unsuitable
 * for large inventory datasets. DECISION: Use AsyncStorage for non-sensitive
 * inventory data (item records are not secrets). API key + session flags use SecureStore.
 * TODO: Revisit when implementing cloud sync (Phase 2+).
 */

import AsyncStorage from '@react-native-async-storage/async-storage';
import * as SecureStore from 'expo-secure-store';
import { APP_CONFIG } from '@/config/app';
import type { Item } from '@/types/item';

const INVENTORY_KEY = APP_CONFIG.STORAGE_KEYS.INVENTORY;

// ─────────────────────────────────────────────────────────────
// INVENTORY CRUD
// ─────────────────────────────────────────────────────────────

/** Load all inventory items from storage */
export async function loadInventory(): Promise<Item[]> {
  const raw = await AsyncStorage.getItem(INVENTORY_KEY);
  if (!raw) return [];
  return JSON.parse(raw) as Item[];
}

/** Save the full inventory array (replaces all) */
export async function saveInventory(items: Item[]): Promise<void> {
  await AsyncStorage.setItem(INVENTORY_KEY, JSON.stringify(items));
}

/** Add a single item to inventory */
export async function addItem(item: Item): Promise<void> {
  const current = await loadInventory();
  current.unshift(item); // newest first
  await saveInventory(current);
}

/** Update a single item by ID */
export async function updateItem(updated: Item): Promise<void> {
  const current = await loadInventory();
  const idx = current.findIndex(i => i.id === updated.id);
  if (idx === -1) throw new Error(`Item ${updated.id} not found.`);
  current[idx] = { ...updated, updatedAt: new Date().toISOString() };
  await saveInventory(current);
}

/** Remove an item by ID */
export async function deleteItem(id: string): Promise<void> {
  const current = await loadInventory();
  await saveInventory(current.filter(i => i.id !== id));
}

/** Get a single item by ID */
export async function getItem(id: string): Promise<Item | null> {
  const items = await loadInventory();
  return items.find(i => i.id === id) ?? null;
}

// ─────────────────────────────────────────────────────────────
// SESSION STATS
// ─────────────────────────────────────────────────────────────

export interface SessionStats {
  totalItemsAllTime: number;
  itemsThisMonth: number;
  monthKey: string;       // 'YYYY-MM'
}

export async function loadSessionStats(): Promise<SessionStats> {
  const raw = await AsyncStorage.getItem(APP_CONFIG.STORAGE_KEYS.SESSION_STATS);
  const now = new Date();
  const monthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  if (!raw) return { totalItemsAllTime: 0, itemsThisMonth: 0, monthKey };
  const stats = JSON.parse(raw) as SessionStats;
  // Reset monthly count if we've crossed into a new month
  if (stats.monthKey !== monthKey) {
    return { ...stats, itemsThisMonth: 0, monthKey };
  }
  return stats;
}

export async function incrementSessionStats(): Promise<SessionStats> {
  const stats = await loadSessionStats();
  const updated: SessionStats = {
    ...stats,
    totalItemsAllTime: stats.totalItemsAllTime + 1,
    itemsThisMonth: stats.itemsThisMonth + 1,
  };
  await AsyncStorage.setItem(APP_CONFIG.STORAGE_KEYS.SESSION_STATS, JSON.stringify(updated));
  return updated;
}

// ─────────────────────────────────────────────────────────────
// ONBOARDING STATE (SecureStore — it's a behavior flag)
// ─────────────────────────────────────────────────────────────

export async function isOnboardingComplete(): Promise<boolean> {
  const val = await SecureStore.getItemAsync(APP_CONFIG.STORAGE_KEYS.ONBOARDING_COMPLETE);
  return val === 'true';
}

export async function markOnboardingComplete(): Promise<void> {
  await SecureStore.setItemAsync(APP_CONFIG.STORAGE_KEYS.ONBOARDING_COMPLETE, 'true');
}

export async function resetOnboarding(): Promise<void> {
  await SecureStore.deleteItemAsync(APP_CONFIG.STORAGE_KEYS.ONBOARDING_COMPLETE);
}
