/**
 * Generated by Computer — lib/stubs.ts
 * Stubbed AI response for development/demo without a real API key.
 * Used by processing.tsx when no API key is configured.
 * REMOVE IN PRODUCTION or gate behind __DEV__ flag.
 */

import type { Category, Protocol, AIResponse } from '@/types/item';

export function STUB_AI_RESPONSE(category: Category, protocol: Protocol): AIResponse {
  const isCore = protocol === 'core';

  const stubs: Record<Category, AIResponse['itemData']['identification']> = {
    SLAB: {
      cardName: 'Charizard',
      set: 'Base Set',
      cardNumber: '4/102',
      game: 'Pokémon',
      gradingCompany: 'PSA',
      grade: '9',
      certNumber: '12345678',
      slabCondition: 'Good',
      cardVariant: 'Holo',
    },
    RAW: {
      cardName: 'Pikachu',
      set: 'Jungle',
      cardNumber: '60/64',
      game: 'Pokémon',
      rarity: 'Common',
      quantity: 1,
      condition: 'NM',
      gradeCandidate: false,
    },
    SEAL: {
      productType: 'Booster Box',
      game: 'Pokémon',
      set: 'Scarlet & Violet 151',
      productName: 'Pokémon TCG: Scarlet & Violet 151 Booster Box',
      language: 'English',
      quantity: 1,
      packagingCondition: 'Mint — factory sealed',
    },
    SHOE: {
      brand: 'Nike',
      model: 'Air Jordan 1 Retro High OG',
      colorway: 'Chicago',
      styleCode: '555088-101',
      size: '10',
      condition: 'DS',
      boxIncluded: true,
      boxCondition: 'Near Mint',
    },
    APRL: {
      brand: 'Supreme',
      itemType: 'Hoodie',
      gender: 'Men',
      size: 'L',
      color: 'Red',
      material: 'Cotton',
      condition: 'NM',
    },
    ELEC: {
      brand: 'Apple',
      productType: 'Laptop',
      modelNumber: 'MLXW3LL/A',
      modelName: 'MacBook Pro 14-inch M1 Pro',
      serialNumber: 'C02G1234MD6T',
      functionalStatus: 'Fully Working',
      physicalCondition: 'Minor wear on lid',
      processor: 'Apple M1 Pro',
      ram: '16GB',
      storage: '512GB SSD',
    },
    COLL: {
      brand: 'Funko',
      productLine: 'Funko Pop',
      characterName: 'Pikachu',
      series: 'Pokémon',
      itemNumber: '353',
      variant: 'GameStop Exclusive',
      retailerExclusive: 'GameStop',
      condition: 'Mint',
      boxCondition: 'Mint',
    },
  };

  const identification = stubs[category];

  const research = isCore
    ? {
        comp1: { price: 350, source: 'eBay sold', date: '2026-03-10', notes: 'Raw sold listing' },
        comp2: { price: 280, source: 'TCGPlayer Low', notes: 'Conservative floor' },
        comp3: { price: 425, source: 'eBay sold', notes: 'Recent high sale' },
        weightedAvg: 350 * 0.5 + 280 * 0.25 + 425 * 0.25,
        targetSellPrice: Math.round((350 * 0.5 + 280 * 0.25 + 425 * 0.25) * 1.07 * 100) / 100,
        minAcceptPrice: Math.round((350 * 0.5 + 280 * 0.25 + 425 * 0.25) * 0.87 * 100) / 100,
        velocityTier: 'Standard' as const,
        marketNotes: '[STUB] Market comps are illustrative. Real comps require live API call.',
      }
    : null;

  const listings = isCore
    ? {
        ebay: {
          title: `[STUB] ${category} Item — Near Mint Condition`,
          description: '[STUB] AI-generated listing description would appear here with full item details, condition notes, and shipping information.',
          price: research?.targetSellPrice ?? 350,
        },
        facebook: {
          title: `[STUB] ${category} for sale`,
          description: '[STUB] Friendly Facebook Marketplace listing copy would appear here.',
          price: research?.minAcceptPrice ?? 300,
        },
        mercari: {
          title: `[STUB] ${category} Item NM`,
          description: '[STUB] Mercari listing copy would appear here.',
          price: research?.targetSellPrice ?? 350,
        },
      }
    : null;

  return {
    itemData: {
      category,
      identification,
      confidence: 92,
      confidenceNotes: undefined,
    },
    research,
    listings,
    inventoryRow: {
      sku: '',
      name: `[STUB] ${category} Item`,
      category,
      condition: 'NM',
      confidence: 92,
      targetSellPrice: research?.targetSellPrice,
      minAcceptPrice: research?.minAcceptPrice,
      notes: 'STUB RESPONSE — no API key configured',
    },
  };
}
