/**
 * Generated by Computer — config/app.ts
 * App-wide configuration constants.
 * Source: photo_intake_engine_spec.docx §6, §7
 */

export const APP_CONFIG = {
  name: 'The Beginning',
  version: '1.0.0',
  company: 'Russell Vault LLC',

  // Freemium limits (Spec §7.1)
  freeTierMonthlyLimit: 10,

  // Photo intake limits
  maxPhotosPerItem: 8,
  minPhotosRequired: 1,

  // Image compression settings (Work Order §2.3)
  imageMaxDimension: 1920,
  imageMaxDimensionSlab: 2048,   // SLAB gets higher res for grade label legibility
  imageQuality: 0.85,

  // API timeout & retry
  apiTimeoutMs: 60_000,
  apiMaxRetries: 1,

  // Storage keys — stored in SecureStore
  STORAGE_KEYS: {
    ANTHROPIC_API_KEY: 'anthropic_api_key',
    ONBOARDING_COMPLETE: 'onboarding_complete',
    USER_PREFERENCES: 'user_preferences',
    INVENTORY: 'inventory_items',
    SESSION_STATS: 'session_stats',
  },

  // Schema version for migration support
  CURRENT_SCHEMA_VERSION: 1,
} as const;
