/**
 * Generated by Computer — config/platforms.ts
 * Platform fee schedule. Source: photo_intake_engine_spec.docx §5.4
 * These are default values; users can override them in Settings (P4-05).
 */

import type { Platform } from '@/types/item';

export interface PlatformConfig {
  id: Platform;
  label: string;
  feePercent: number;       // default fee as decimal (e.g. 0.13 = 13%)
  appliesTo: string[];      // category IDs this platform typically serves
  notes: string;
}

export const PLATFORMS: PlatformConfig[] = [
  {
    id: 'ebay',
    label: 'eBay',
    feePercent: 0.13,
    appliesTo: ['SLAB', 'RAW', 'SEAL', 'SHOE', 'APRL', 'ELEC', 'COLL'],
    notes: 'Standard final value fee. Promoted listings add ~3–5% more.',
  },
  {
    id: 'mercari',
    label: 'Mercari',
    feePercent: 0.13,
    appliesTo: ['SLAB', 'RAW', 'SEAL', 'SHOE', 'APRL', 'ELEC', 'COLL'],
    notes: 'Flat seller fee.',
  },
  {
    id: 'tcgplayer',
    label: 'TCGPlayer',
    feePercent: 0.125,
    appliesTo: ['SLAB', 'RAW', 'SEAL'],
    notes: 'Includes payment processing.',
  },
  {
    id: 'facebook',
    label: 'Facebook Marketplace',
    feePercent: 0.05,
    appliesTo: ['SLAB', 'RAW', 'SEAL', 'SHOE', 'APRL', 'ELEC', 'COLL'],
    notes: 'Applies to shipped sales only. Local pickup is free.',
  },
  {
    id: 'stockx',
    label: 'StockX',
    feePercent: 0.10,
    appliesTo: ['SHOE', 'APRL'],
    notes: "Seller fee. Buyer premium is separate.",
  },
  {
    id: 'goat',
    label: 'GOAT',
    feePercent: 0.095,
    appliesTo: ['SHOE'],
    notes: 'Standard commission. Varies with seller level.',
  },
];

export const PLATFORM_MAP: Record<Platform, PlatformConfig> = Object.fromEntries(
  PLATFORMS.map(p => [p.id, p])
) as Record<Platform, PlatformConfig>;

/** Calculate platform fee for a given sale price */
export function calcPlatformFee(platform: Platform, salePrice: number): number {
  const config = PLATFORM_MAP[platform];
  return salePrice * config.feePercent;
}
