/**
 * Generated by Computer — app/(tabs)/analytics.tsx
 * Analytics tab — placeholder for Work Order Phase 4 (P4-01).
 * Full build: time range, revenue, category performance, velocity, platform dist.
 * Source: TheBeginning_WorkOrder_v1.0.docx §4.4
 */

import { View, Text } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useInventoryStore } from '@/store/inventory';

export default function AnalyticsScreen() {
  const items = useInventoryStore((s) => s.items);
  const soldItems = items.filter((i) => i.status === 'Sold');
  const totalRevenue = soldItems.reduce((sum, i) => sum + (i.sale?.salePrice ?? 0), 0);
  const totalCost = soldItems.reduce((sum, i) => sum + (i.purchasePrice ?? 0), 0);
  const netProfit = soldItems.reduce((sum, i) => sum + (i.sale?.netProfit ?? 0), 0);

  return (
    <SafeAreaView className="flex-1 bg-[#0a0a0a]" edges={['bottom']}>
      <View className="flex-1 px-4 pt-4">
        {/* Summary cards */}
        <View className="flex-row flex-wrap gap-3 mb-6">
          <SummaryCard label="Total Revenue" value={`$${totalRevenue.toFixed(2)}`} color="#22c55e" />
          <SummaryCard label="Total Cost" value={`$${totalCost.toFixed(2)}`} color="#ef4444" />
          <SummaryCard label="Net Profit" value={`$${netProfit.toFixed(2)}`} color={netProfit >= 0 ? '#22c55e' : '#ef4444'} />
          <SummaryCard label="Items Sold" value={String(soldItems.length)} color="#6366f1" />
        </View>

        {/* TODO placeholder */}
        <View className="flex-1 items-center justify-center">
          <Text className="text-[#52525b] text-lg font-semibold">Full Analytics — Phase 4</Text>
          <Text className="text-[#52525b] text-sm text-center mt-2 px-8">
            Revenue charts, category performance, velocity analysis, and platform breakdown coming in Work Order Phase 4 (P4-01).
          </Text>
        </View>
      </View>
    </SafeAreaView>
  );
}

function SummaryCard({ label, value, color }: { label: string; value: string; color: string }) {
  return (
    <View className="flex-1 min-w-[44%] bg-[#141414] border border-[#27272a] rounded-xl p-4">
      <Text className="text-[#a1a1aa] text-xs mb-1">{label}</Text>
      <Text className="text-xl font-bold" style={{ color }}>{value}</Text>
    </View>
  );
}
