/**
 * Generated by Computer — app/(tabs)/index.tsx
 * S-02: Home / Dashboard screen.
 * Vertical slice: Quick-launch category buttons + recent items list.
 * Full dashboard rebuild is Work Order P2-01 (Phase 2).
 * Source: TheBeginning_WorkOrder_v1.0.docx §4.1; photo_intake_engine_spec.docx §3.2
 */

import { View, Text, ScrollView, Pressable, FlatList } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useInventoryStore } from '@/store/inventory';
import { useSessionStore } from '@/store/session';
import { useIntakeStore } from '@/store/intake';
import { CATEGORIES } from '@/types/categories';

export default function HomeScreen() {
  const router = useRouter();
  const items = useInventoryStore((s) => s.items);
  const { remainingFreeItems, isPro } = useSessionStore();
  const resetIntake = useIntakeStore((s) => s.reset);

  const recentItems = items.slice(0, 5);

  function handleStartIntake() {
    resetIntake();
    router.push('/intake/category');
  }

  return (
    <SafeAreaView className="flex-1 bg-[#0a0a0a]" edges={['bottom']}>
      <ScrollView className="flex-1" contentContainerStyle={{ paddingBottom: 24 }}>
        {/* Header stats */}
        <View className="px-4 pt-4 pb-2">
          <View className="flex-row gap-3">
            <StatCard label="Total Items" value={String(items.length)} />
            <StatCard
              label={isPro ? 'Pro Plan' : 'Free Tier'}
              value={isPro ? '∞' : `${remainingFreeItems()} left`}
              accent={isPro ? '#22c55e' : '#f59e0b'}
            />
          </View>
        </View>

        {/* Big add button */}
        <View className="px-4 py-4">
          <Pressable
            onPress={handleStartIntake}
            className="bg-[#6366f1] rounded-2xl p-5 items-center active:opacity-80"
          >
            <Text className="text-white text-xl font-bold tracking-wide">+ ADD ITEM</Text>
            <Text className="text-[#c7d2fe] text-sm mt-1">Photo → AI → Inventory</Text>
          </Pressable>
        </View>

        {/* Category quick-launch grid */}
        <View className="px-4">
          <Text className="text-[#a1a1aa] text-xs font-semibold tracking-widest mb-3">CATEGORIES</Text>
          <View className="flex-row flex-wrap gap-2">
            {CATEGORIES.map((cat) => (
              <Pressable
                key={cat.id}
                onPress={() => {
                  resetIntake();
                  useIntakeStore.getState().setCategory(cat.id);
                  router.push('/intake/protocol');
                }}
                className="flex-1 min-w-[28%] rounded-xl p-3 items-center active:opacity-70"
                style={{ backgroundColor: cat.color + '22' }}
              >
                <Text className="text-2xl mb-1">{cat.icon}</Text>
                <Text className="font-bold text-[#f4f4f5] text-sm">{cat.label}</Text>
                <Text className="text-[#a1a1aa] text-xs">{cat.sub}</Text>
              </Pressable>
            ))}
          </View>
        </View>

        {/* Recent items */}
        {recentItems.length > 0 && (
          <View className="px-4 mt-6">
            <Text className="text-[#a1a1aa] text-xs font-semibold tracking-widest mb-3">RECENT ITEMS</Text>
            {recentItems.map((item) => (
              <Pressable
                key={item.id}
                onPress={() => router.push(`/item/${item.id}`)}
                className="bg-[#141414] border border-[#27272a] rounded-xl p-4 mb-2 active:opacity-80"
              >
                <View className="flex-row justify-between items-start">
                  <Text className="text-[#f4f4f5] font-semibold flex-1 mr-2" numberOfLines={1}>
                    {item.sku}
                  </Text>
                  <Text className="text-[#6366f1] text-xs font-bold">{item.category}</Text>
                </View>
                <Text className="text-[#a1a1aa] text-xs mt-1">{item.status}</Text>
              </Pressable>
            ))}
            <Pressable onPress={() => router.push('/inventory')} className="mt-1">
              <Text className="text-[#6366f1] text-sm font-semibold text-center py-2">
                View All Inventory →
              </Text>
            </Pressable>
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

function StatCard({
  label,
  value,
  accent = '#6366f1',
}: {
  label: string;
  value: string;
  accent?: string;
}) {
  return (
    <View className="flex-1 bg-[#141414] border border-[#27272a] rounded-xl p-4">
      <Text className="text-[#a1a1aa] text-xs mb-1">{label}</Text>
      <Text className="text-2xl font-bold" style={{ color: accent }}>
        {value}
      </Text>
    </View>
  );
}
