/**
 * Generated by Computer — app/(tabs)/inventory.tsx
 * S-11: Inventory List screen.
 * Vertical slice: list + filter by category + item detail tap.
 * Full rebuild with FlashList, search, filters is Work Order P2-02–P2-04.
 * Source: TheBeginning_WorkOrder_v1.0.docx §4.2
 */

import { useState } from 'react';
import { View, Text, FlatList, Pressable, TextInput } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useInventoryStore } from '@/store/inventory';
import type { Category, Item } from '@/types/item';
import { CATEGORIES } from '@/types/categories';

const ALL_FILTER = 'ALL' as const;
type FilterValue = Category | typeof ALL_FILTER;

export default function InventoryScreen() {
  const router = useRouter();
  const items = useInventoryStore((s) => s.items);
  const [filter, setFilter] = useState<FilterValue>(ALL_FILTER);
  const [search, setSearch] = useState('');

  const filtered = items.filter((item) => {
    const matchCat = filter === ALL_FILTER || item.category === filter;
    const q = search.toLowerCase();
    const matchSearch =
      !q ||
      item.sku.toLowerCase().includes(q) ||
      item.category.toLowerCase().includes(q) ||
      item.status.toLowerCase().includes(q);
    return matchCat && matchSearch;
  });

  const totalValue = items
    .filter((i) => i.research?.targetSellPrice)
    .reduce((sum, i) => sum + (i.research?.targetSellPrice ?? 0), 0);

  return (
    <SafeAreaView className="flex-1 bg-[#0a0a0a]" edges={['bottom']}>
      {/* Header value row */}
      <View className="px-4 pt-3 pb-2 border-b border-[#27272a]">
        <View className="flex-row justify-between items-center">
          <Text className="text-[#a1a1aa] text-sm">
            {filtered.length} items
          </Text>
          <Text className="text-[#22c55e] text-sm font-semibold">
            ${totalValue.toFixed(2)} est. value
          </Text>
        </View>
        {/* Search */}
        <TextInput
          className="mt-2 bg-[#141414] border border-[#27272a] rounded-xl px-4 py-2.5 text-[#f4f4f5]"
          placeholder="Search SKU, category, status..."
          placeholderTextColor="#52525b"
          value={search}
          onChangeText={setSearch}
        />
      </View>

      {/* Category filter chips */}
      <View className="py-2 border-b border-[#27272a]">
        <FlatList
          horizontal
          data={[ALL_FILTER, ...CATEGORIES.map((c) => c.id)] as FilterValue[]}
          keyExtractor={(i) => i}
          contentContainerStyle={{ paddingHorizontal: 16 }}
          showsHorizontalScrollIndicator={false}
          renderItem={({ item: f }) => {
            const cat = CATEGORIES.find((c) => c.id === f);
            const isActive = filter === f;
            return (
              <Pressable
                onPress={() => setFilter(f)}
                className="mr-2 px-3 py-1.5 rounded-full"
                style={{
                  backgroundColor: isActive
                    ? cat?.color ?? '#6366f1'
                    : '#1c1c1c',
                  borderWidth: 1,
                  borderColor: isActive ? 'transparent' : '#27272a',
                }}
              >
                <Text
                  className="text-xs font-semibold"
                  style={{ color: isActive ? '#0a0a0a' : '#a1a1aa' }}
                >
                  {f === ALL_FILTER ? 'ALL' : `${cat?.icon} ${f}`}
                </Text>
              </Pressable>
            );
          }}
        />
      </View>

      {/* Item list */}
      <FlatList
        data={filtered}
        keyExtractor={(i) => i.id}
        contentContainerStyle={{ padding: 16, paddingBottom: 32 }}
        ListEmptyComponent={
          <View className="items-center py-20">
            <Text className="text-[#52525b] text-lg mb-2">No items found</Text>
            <Text className="text-[#52525b] text-sm text-center">
              {items.length === 0
                ? 'Tap + ADD ITEM on the Home screen to get started.'
                : 'Try adjusting your filter or search.'}
            </Text>
          </View>
        }
        renderItem={({ item }) => <InventoryRow item={item} onPress={() => router.push(`/item/${item.id}`)} />}
      />
    </SafeAreaView>
  );
}

function InventoryRow({ item, onPress }: { item: Item; onPress: () => void }) {
  const cat = CATEGORIES.find((c) => c.id === item.category);
  return (
    <Pressable
      onPress={onPress}
      className="bg-[#141414] border border-[#27272a] rounded-xl p-4 mb-2 active:opacity-75"
    >
      <View className="flex-row justify-between items-start mb-1">
        <Text className="text-[#f4f4f5] font-bold text-base flex-1 mr-2" numberOfLines={1}>
          {item.sku}
        </Text>
        <View
          className="px-2 py-0.5 rounded-full"
          style={{ backgroundColor: (cat?.color ?? '#6366f1') + '33' }}
        >
          <Text className="text-xs font-semibold" style={{ color: cat?.color ?? '#6366f1' }}>
            {item.category}
          </Text>
        </View>
      </View>
      <View className="flex-row justify-between items-center">
        <Text className="text-[#a1a1aa] text-sm">{item.status}</Text>
        {item.research?.targetSellPrice ? (
          <Text className="text-[#22c55e] text-sm font-semibold">
            ${item.research.targetSellPrice.toFixed(2)}
          </Text>
        ) : (
          <ConfidenceDot confidence={item.confidence} />
        )}
      </View>
    </Pressable>
  );
}

function ConfidenceDot({ confidence }: { confidence: number }) {
  const color =
    confidence >= 85 ? '#22c55e' : confidence >= 65 ? '#f59e0b' : '#ef4444';
  return (
    <View className="flex-row items-center gap-1">
      <View className="w-2 h-2 rounded-full" style={{ backgroundColor: color }} />
      <Text className="text-xs" style={{ color }}>{confidence}%</Text>
    </View>
  );
}
