/**
 * Generated by Computer — app/(tabs)/settings.tsx
 * S-13: Settings screen. Vertical slice: API key management.
 * Full settings rebuild is Work Order P4-06 (Phase 4).
 * Source: TheBeginning_WorkOrder_v1.0.docx §4.8; photo_intake_engine_spec.docx §3.1
 */

import { useState } from 'react';
import { View, Text, TextInput, Pressable, ScrollView, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { saveApiKey, getApiKey, revokeApiKey } from '@/lib/api';
import { MODEL_PRIMARY, MODEL_FALLBACK } from '@/lib/models';
import { APP_CONFIG } from '@/config/app';
import { useEffect } from 'react';

export default function SettingsScreen() {
  const [apiKeyInput, setApiKeyInput] = useState('');
  const [savedKeyPreview, setSavedKeyPreview] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [keyStatus, setKeyStatus] = useState<'idle' | 'valid' | 'invalid'>('idle');

  useEffect(() => {
    loadKeyPreview();
  }, []);

  async function loadKeyPreview() {
    const key = await getApiKey();
    if (key) {
      setSavedKeyPreview('••••' + key.slice(-4));
    }
  }

  async function handleSaveKey() {
    if (!apiKeyInput.trim()) return;
    setIsSaving(true);
    const result = await saveApiKey(apiKeyInput.trim());
    setIsSaving(false);
    if (result.success) {
      setKeyStatus('valid');
      setApiKeyInput('');
      loadKeyPreview();
    } else {
      setKeyStatus('invalid');
      Alert.alert('Key Error', result.error ?? 'Failed to validate key.');
    }
  }

  async function handleRevokeKey() {
    Alert.alert(
      'Remove API Key',
      'This will delete your saved key. You will need to re-enter it to use the AI features.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Remove', style: 'destructive',
          onPress: async () => {
            await revokeApiKey();
            setSavedKeyPreview(null);
            setKeyStatus('idle');
          },
        },
      ]
    );
  }

  return (
    <SafeAreaView className="flex-1 bg-[#0a0a0a]" edges={['bottom']}>
      <ScrollView className="flex-1 px-4 pt-4">
        {/* API Key section */}
        <SectionHeader title="API KEY" />
        <View className="bg-[#141414] border border-[#27272a] rounded-xl p-4 mb-4">
          {savedKeyPreview ? (
            <View className="flex-row justify-between items-center mb-3">
              <View>
                <Text className="text-[#a1a1aa] text-xs mb-0.5">Current Key</Text>
                <Text className="text-[#22c55e] font-mono font-semibold">{savedKeyPreview}</Text>
              </View>
              <Pressable onPress={handleRevokeKey} className="px-3 py-1.5 bg-[#1c1c1c] border border-[#ef4444] rounded-lg">
                <Text className="text-[#ef4444] text-xs font-semibold">Revoke</Text>
              </Pressable>
            </View>
          ) : (
            <Text className="text-[#f59e0b] text-xs mb-3">
              ⚠️ No API key set. Enter your Anthropic key below to enable AI features.
            </Text>
          )}
          <TextInput
            className="bg-[#0a0a0a] border border-[#27272a] rounded-xl px-4 py-3 text-[#f4f4f5] font-mono text-sm"
            placeholder="sk-ant-..."
            placeholderTextColor="#52525b"
            value={apiKeyInput}
            onChangeText={setApiKeyInput}
            secureTextEntry
            autoCapitalize="none"
            autoCorrect={false}
          />
          <Pressable
            onPress={handleSaveKey}
            disabled={isSaving || !apiKeyInput.trim()}
            className="mt-3 bg-[#6366f1] rounded-xl py-3 items-center active:opacity-80"
            style={{ opacity: (!apiKeyInput.trim() || isSaving) ? 0.5 : 1 }}
          >
            <Text className="text-white font-bold">
              {isSaving ? 'Validating...' : 'Save & Validate Key'}
            </Text>
          </Pressable>
          <Text className="text-[#52525b] text-xs mt-3">
            Your key is stored in device secure storage and never sent anywhere except Anthropic's API.
          </Text>
        </View>

        {/* App Info */}
        <SectionHeader title="APP INFO" />
        <View className="bg-[#141414] border border-[#27272a] rounded-xl p-4 mb-4">
          <InfoRow label="Version" value={APP_CONFIG.version} />
          <InfoRow label="Primary Model" value={MODEL_PRIMARY} />
          <InfoRow label="Fallback Model" value={MODEL_FALLBACK} />
          <InfoRow label="Schema Version" value={String(APP_CONFIG.CURRENT_SCHEMA_VERSION)} />
        </View>

        {/* TODO Phase 4 items */}
        <SectionHeader title="COMING IN PHASE 4 (P4-06)" />
        <View className="bg-[#141414] border border-[#27272a] rounded-xl p-4 mb-8">
          {[
            'Default protocol per category',
            'Platform fee configuration',
            'Storage location defaults',
            'Data export (CSV / JSON)',
            'Onboarding reset',
          ].map((item) => (
            <Text key={item} className="text-[#52525b] text-sm py-1.5 border-b border-[#1c1c1c] last:border-0">
              · {item}
            </Text>
          ))}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

function SectionHeader({ title }: { title: string }) {
  return (
    <Text className="text-[#a1a1aa] text-xs font-semibold tracking-widest mb-2 mt-2">
      {title}
    </Text>
  );
}

function InfoRow({ label, value }: { label: string; value: string }) {
  return (
    <View className="flex-row justify-between py-2 border-b border-[#1c1c1c] last:border-0">
      <Text className="text-[#a1a1aa] text-sm">{label}</Text>
      <Text className="text-[#f4f4f5] text-sm font-mono flex-1 text-right ml-4" numberOfLines={1}>{value}</Text>
    </View>
  );
}
