/**
 * Generated by Computer — app/item/[id].tsx
 * S-12: Item Detail screen. Vertical slice: full record view.
 * Full rebuild with photo gallery, status timeline, edit, action buttons is Work Order P2-05.
 * Source: TheBeginning_WorkOrder_v1.0.docx §4.3
 */

import { ScrollView, View, Text, Pressable, Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useInventoryStore } from '@/store/inventory';
import { CATEGORY_MAP } from '@/types/categories';
import { formatUSD } from '@/lib/pricing';
import type { ItemStatus } from '@/types/item';

const STATUS_ORDER: ItemStatus[] = ['Intake', 'Photo Queue', 'Research', 'Listed', 'Sold', 'Shipped'];

export default function ItemDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const item = useInventoryStore((s) => s.getItemById(id));
  const deleteItem = useInventoryStore((s) => s.deleteItem);
  const updateStatus = useInventoryStore((s) => s.updateStatus);

  if (!item) {
    return (
      <SafeAreaView className="flex-1 bg-[#0a0a0a] items-center justify-center">
        <Text className="text-[#a1a1aa]">Item not found.</Text>
        <Pressable onPress={() => router.back()} className="mt-4">
          <Text className="text-[#6366f1]">← Go Back</Text>
        </Pressable>
      </SafeAreaView>
    );
  }

  const cat = CATEGORY_MAP[item.category];

  function handleDelete() {
    Alert.alert('Delete Item', `Delete ${item.sku}? This cannot be undone.`, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: () => {
          deleteItem(id);
          router.back();
        },
      },
    ]);
  }

  return (
    <SafeAreaView className="flex-1 bg-[#0a0a0a]" edges={['bottom']}>
      <ScrollView className="flex-1" contentContainerStyle={{ padding: 16, paddingBottom: 40 }}>
        {/* Hero header */}
        <View className="flex-row justify-between items-start mb-4">
          <View>
            <Text className="text-[#f4f4f5] font-bold text-2xl">{item.sku}</Text>
            <View className="flex-row gap-2 mt-1 flex-wrap">
              <Badge text={cat.label} color={cat.color} />
              <Badge text={item.protocol.toUpperCase()} color="#6366f1" />
              <Badge text={item.status} color={item.status === 'Sold' ? '#22c55e' : '#a1a1aa'} />
            </View>
          </View>
          <View
            className="w-12 h-12 rounded-xl items-center justify-center"
            style={{ backgroundColor: cat.color + '22' }}
          >
            <Text className="text-2xl">{cat.icon}</Text>
          </View>
        </View>

        {/* Identification */}
        <Section title="IDENTIFICATION">
          {Object.entries(item.identification).map(([k, v]) =>
            v !== undefined && v !== '' ? (
              <Row key={k} label={k.replace(/([A-Z])/g, ' $1')} value={String(v)} />
            ) : null
          )}
          <Row label="Confidence" value={`${item.confidence}%`} />
          {item.confidenceNotes && (
            <Text className="text-[#f59e0b] text-xs mt-2 p-2 bg-[#f59e0b15] rounded-lg">
              {item.confidenceNotes}
            </Text>
          )}
        </Section>

        {/* Research / Pricing — CORE only */}
        {item.research && (
          <Section title="PRICING">
            <Row label="Target Sell" value={formatUSD(item.research.targetSellPrice)} highlight="#22c55e" />
            <Row label="Min Accept" value={formatUSD(item.research.minAcceptPrice)} highlight="#f59e0b" />
            <Row label="Weighted Avg" value={formatUSD(item.research.weightedAvg)} />
            <Row label="Velocity" value={item.research.velocityTier} />
            {item.research.marketNotes && (
              <Text className="text-[#a1a1aa] text-xs mt-2">{item.research.marketNotes}</Text>
            )}
          </Section>
        )}

        {/* Purchase info */}
        <Section title="PURCHASE">
          <Row label="Purchase Price" value={item.purchasePrice ? formatUSD(item.purchasePrice) : '—'} />
          <Row label="Source" value={item.purchaseSource ?? '—'} />
          <Row label="Storage" value={item.storageLocation ?? '—'} />
          <Row label="Date" value={item.purchaseDate ?? '—'} />
        </Section>

        {/* Status timeline */}
        <Section title="STATUS HISTORY">
          {item.statusHistory.map((entry, i) => (
            <View key={i} className="flex-row gap-3 mb-2">
              <View className="w-2 h-2 rounded-full bg-[#6366f1] mt-1.5" />
              <View>
                <Text className="text-[#f4f4f5] text-sm font-semibold">{entry.status}</Text>
                <Text className="text-[#52525b] text-xs">
                  {new Date(entry.timestamp).toLocaleString()}
                </Text>
              </View>
            </View>
          ))}
        </Section>

        {/* Actions */}
        <Section title="ACTIONS">
          <View className="gap-2">
            {STATUS_ORDER.filter((s) => s !== item.status).map((nextStatus) => (
              <Pressable
                key={nextStatus}
                onPress={() => updateStatus([item.id], nextStatus)}
                className="bg-[#141414] border border-[#27272a] rounded-xl py-3 px-4"
              >
                <Text className="text-[#6366f1] font-semibold">Mark as {nextStatus}</Text>
              </Pressable>
            ))}
            <Pressable
              onPress={handleDelete}
              className="bg-[#ef444420] border border-[#ef4444] rounded-xl py-3 px-4 mt-2"
            >
              <Text className="text-[#ef4444] font-semibold text-center">Delete Item</Text>
            </Pressable>
          </View>
        </Section>

        {/* Metadata */}
        <View className="mt-4">
          <Text className="text-[#52525b] text-xs">Created: {new Date(item.createdAt).toLocaleString()}</Text>
          <Text className="text-[#52525b] text-xs">Updated: {new Date(item.updatedAt).toLocaleString()}</Text>
          <Text className="text-[#52525b] text-xs">Schema v{item.schemaVersion}</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View className="mb-5">
      <Text className="text-[#a1a1aa] text-xs font-semibold tracking-widest mb-2">{title}</Text>
      <View className="bg-[#141414] border border-[#27272a] rounded-xl p-4">
        {children}
      </View>
    </View>
  );
}

function Row({ label, value, highlight }: { label: string; value: string; highlight?: string }) {
  return (
    <View className="flex-row justify-between py-2 border-b border-[#1c1c1c] last:border-0">
      <Text className="text-[#a1a1aa] text-sm capitalize">{label}</Text>
      <Text
        className="text-sm font-medium flex-1 text-right ml-4"
        style={{ color: highlight ?? '#f4f4f5' }}
        numberOfLines={2}
      >
        {value}
      </Text>
    </View>
  );
}

function Badge({ text, color }: { text: string; color: string }) {
  return (
    <View className="px-2 py-0.5 rounded-full" style={{ backgroundColor: color + '33' }}>
      <Text className="text-xs font-semibold" style={{ color }}>{text}</Text>
    </View>
  );
}
